In [ ]:
%config Completer.use_jedi = False

1 - [Introducción](#intro)

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introducción" data-toc-modified-id="Introducción-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introducción</a></span></li><li><span><a href="#Instalación" data-toc-modified-id="Instalación-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Instalación</a></span></li><li><span><a href="#Introducción-a-las-estructuras-de-datos-de-pandas" data-toc-modified-id="Introducción-a-las-estructuras-de-datos-de-pandas-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Introducción a las estructuras de datos de pandas</a></span><ul class="toc-item"><li><span><a href="#Series" data-toc-modified-id="Series-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Series</a></span></li><li><span><a href="#Buscar-valores-NaN" data-toc-modified-id="Buscar-valores-NaN-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Buscar valores NaN</a></span></li></ul></li><li><span><a href="#Datos-de-lectura/escritura" data-toc-modified-id="Datos-de-lectura/escritura-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Datos de lectura/escritura</a></span><ul class="toc-item"><li><span><a href="#Cargamos-datos-de-formato-CSV" data-toc-modified-id="Cargamos-datos-de-formato-CSV-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Cargamos datos de formato CSV</a></span></li><li><span><a href="#Cargamos-datos-de-formato-xlsx" data-toc-modified-id="Cargamos-datos-de-formato-xlsx-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Cargamos datos de formato xlsx</a></span></li><li><span><a href="#Visualizamos-las-primeras-filas" data-toc-modified-id="Visualizamos-las-primeras-filas-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Visualizamos las primeras filas</a></span></li><li><span><a href="#Visualizamos-las-últimas-filas" data-toc-modified-id="Visualizamos-las-últimas-filas-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Visualizamos las últimas filas</a></span></li><li><span><a href="#Visualizamos-una-muestra-aleatoria" data-toc-modified-id="Visualizamos-una-muestra-aleatoria-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>Visualizamos una muestra aleatoria</a></span></li></ul></li><li><span><a href="#Análisis-exploratorio-de-un-dataframe" data-toc-modified-id="Análisis-exploratorio-de-un-dataframe-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Análisis exploratorio de un dataframe</a></span></li><li><span><a href="#Operaciones-básicas-con-los-dataframes" data-toc-modified-id="Operaciones-básicas-con-los-dataframes-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Operaciones básicas con los dataframes</a></span><ul class="toc-item"><li><span><a href="#Seleccionamos-una-columna" data-toc-modified-id="Seleccionamos-una-columna-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Seleccionamos una columna</a></span></li><li><span><a href="#Seleccionamos-varias-columnas" data-toc-modified-id="Seleccionamos-varias-columnas-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Seleccionamos varias columnas</a></span></li></ul></li><li><span><a href="#siN-EMBARGO.....-🚨º" data-toc-modified-id="siN-EMBARGO.....-🚨º-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>siN EMBARGO..... 🚨º</a></span><ul class="toc-item"><li><span><a href="#Obtener-los-valores-únicos-de-una-columna-(es-decir,-una-serie)" data-toc-modified-id="Obtener-los-valores-únicos-de-una-columna-(es-decir,-una-serie)-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Obtener los valores únicos de una columna (es decir, una serie)</a></span></li><li><span><a href="#Cambiar-el-tipo-de-datos-de-una-columna" data-toc-modified-id="Cambiar-el-tipo-de-datos-de-una-columna-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Cambiar el tipo de datos de una columna</a></span></li><li><span><a href="#Filtramos-los-datos-por-el-valor-de-las-columnas" data-toc-modified-id="Filtramos-los-datos-por-el-valor-de-las-columnas-7.3"><span class="toc-item-num">7.3&nbsp;&nbsp;</span>Filtramos los datos por el valor de las columnas</a></span></li><li><span><a href="#Copia-de-un-dataframe-y-renombrar-columnas" data-toc-modified-id="Copia-de-un-dataframe-y-renombrar-columnas-7.4"><span class="toc-item-num">7.4&nbsp;&nbsp;</span>Copia de un dataframe y renombrar columnas</a></span><ul class="toc-item"><li><span><a href="#Renombramos-columnas" data-toc-modified-id="Renombramos-columnas-7.4.1"><span class="toc-item-num">7.4.1&nbsp;&nbsp;</span>Renombramos columnas</a></span></li><li><span><a href="#Podemos-renombrar-las-columnas-machacando-el-atributo-de-la-instancia...-¿os-suena-esto?" data-toc-modified-id="Podemos-renombrar-las-columnas-machacando-el-atributo-de-la-instancia...-¿os-suena-esto?-7.4.2"><span class="toc-item-num">7.4.2&nbsp;&nbsp;</span>Podemos renombrar las columnas machacando el atributo de la instancia... ¿os suena esto?</a></span></li></ul></li><li><span><a href="#Borramos-columnas" data-toc-modified-id="Borramos-columnas-7.5"><span class="toc-item-num">7.5&nbsp;&nbsp;</span>Borramos columnas</a></span></li><li><span><a href="#Borramos-filas" data-toc-modified-id="Borramos-filas-7.6"><span class="toc-item-num">7.6&nbsp;&nbsp;</span>Borramos filas</a></span></li><li><span><a href="#Reset_index-y-set_index" data-toc-modified-id="Reset_index-y-set_index-7.7"><span class="toc-item-num">7.7&nbsp;&nbsp;</span>Reset_index y set_index</a></span><ul class="toc-item"><li><span><a href="#SET_INDEX" data-toc-modified-id="SET_INDEX-7.7.1"><span class="toc-item-num">7.7.1&nbsp;&nbsp;</span>SET_INDEX</a></span></li></ul></li><li><span><a href="#Operaciones-entre-columnas" data-toc-modified-id="Operaciones-entre-columnas-7.8"><span class="toc-item-num">7.8&nbsp;&nbsp;</span>Operaciones entre columnas</a></span></li></ul></li><li><span><a href="#Apply-!!" data-toc-modified-id="Apply-!!-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Apply !!</a></span></li><li><span><a href="#Df-.loc-e-.iloc" data-toc-modified-id="Df-.loc-e-.iloc-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Df .loc e .iloc</a></span><ul class="toc-item"><li><span><a href="#Seleccionar-filas-y-columnas-en-Pandas-mediante-posición-con-iloc" data-toc-modified-id="Seleccionar-filas-y-columnas-en-Pandas-mediante-posición-con-iloc-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>Seleccionar filas y columnas en Pandas mediante posición con iloc</a></span></li><li><span><a href="#Seleccionar-filas-y-columnas-en-Pandas-en-base-a-etiquetas-con-loc" data-toc-modified-id="Seleccionar-filas-y-columnas-en-Pandas-en-base-a-etiquetas-con-loc-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>Seleccionar filas y columnas en Pandas en base a etiquetas con loc</a></span><ul class="toc-item"><li><span><a href="#En-base-a-etiqueta" data-toc-modified-id="En-base-a-etiqueta-9.2.1"><span class="toc-item-num">9.2.1&nbsp;&nbsp;</span>En base a etiqueta</a></span></li></ul></li></ul></li><li><span><a href="#Ordenamos-un-dataframe" data-toc-modified-id="Ordenamos-un-dataframe-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Ordenamos un dataframe</a></span><ul class="toc-item"><li><span><a href="#Buscamos-valores-nulos" data-toc-modified-id="Buscamos-valores-nulos-10.1"><span class="toc-item-num">10.1&nbsp;&nbsp;</span>Buscamos valores nulos</a></span><ul class="toc-item"><li><span><a href="#¿Es-nulo?" data-toc-modified-id="¿Es-nulo?-10.1.1"><span class="toc-item-num">10.1.1&nbsp;&nbsp;</span>¿Es nulo?</a></span></li><li><span><a href="#¿Es-NO-nulo?" data-toc-modified-id="¿Es-NO-nulo?-10.1.2"><span class="toc-item-num">10.1.2&nbsp;&nbsp;</span>¿Es NO nulo?</a></span></li><li><span><a href="#Sacar-una-suma-de-los-valores-nulos-de-cada-columna" data-toc-modified-id="Sacar-una-suma-de-los-valores-nulos-de-cada-columna-10.1.3"><span class="toc-item-num">10.1.3&nbsp;&nbsp;</span>Sacar una suma de los valores nulos de cada columna</a></span></li></ul></li><li><span><a href="#Borramos-los-valores-nulos" data-toc-modified-id="Borramos-los-valores-nulos-10.2"><span class="toc-item-num">10.2&nbsp;&nbsp;</span>Borramos los valores nulos</a></span></li><li><span><a href="#Cómo-rellenar-los-datos-que-faltan" data-toc-modified-id="Cómo-rellenar-los-datos-que-faltan-10.3"><span class="toc-item-num">10.3&nbsp;&nbsp;</span>Cómo rellenar los datos que faltan</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#CATEGÓRICAS-EN-DATAFRAME-Y-DEJAR-DOCUMENTACIÓN" data-toc-modified-id="CATEGÓRICAS-EN-DATAFRAME-Y-DEJAR-DOCUMENTACIÓN-10.3.0.1"><span class="toc-item-num">10.3.0.1&nbsp;&nbsp;</span>CATEGÓRICAS EN DATAFRAME Y DEJAR DOCUMENTACIÓN</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#Borramos-los-duplicados" data-toc-modified-id="Borramos-los-duplicados-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Borramos los duplicados</a></span></li><li><span><a href="#Agregación-de-datos" data-toc-modified-id="Agregación-de-datos-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Agregación de datos</a></span><ul class="toc-item"><li><span><a href="#GroupBy" data-toc-modified-id="GroupBy-12.1"><span class="toc-item-num">12.1&nbsp;&nbsp;</span>GroupBy</a></span><ul class="toc-item"><li><span><a href="#Me-preguntaréis-¿y-si-quiero-agrupar-por-más-columnas?" data-toc-modified-id="Me-preguntaréis-¿y-si-quiero-agrupar-por-más-columnas?-12.1.1"><span class="toc-item-num">12.1.1&nbsp;&nbsp;</span>Me preguntaréis ¿y si quiero agrupar por más columnas?</a></span></li></ul></li><li><span><a href="#Unión-de-Dataframes" data-toc-modified-id="Unión-de-Dataframes-12.2"><span class="toc-item-num">12.2&nbsp;&nbsp;</span>Unión de Dataframes</a></span></li><li><span><a href="#Concat" data-toc-modified-id="Concat-12.3"><span class="toc-item-num">12.3&nbsp;&nbsp;</span>Concat</a></span></li><li><span><a href="#Merge" data-toc-modified-id="Merge-12.4"><span class="toc-item-num">12.4&nbsp;&nbsp;</span>Merge</a></span></li><li><span><a href="#Join" data-toc-modified-id="Join-12.5"><span class="toc-item-num">12.5&nbsp;&nbsp;</span>Join</a></span></li></ul></li><li><span><a href="#Exportar-datos" data-toc-modified-id="Exportar-datos-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>Exportar datos</a></span></li><li><span><a href="#Métodos-habituales-de-pandas" data-toc-modified-id="Métodos-habituales-de-pandas-14"><span class="toc-item-num">14&nbsp;&nbsp;</span>Métodos habituales de pandas</a></span></li><li><span><a href="#Resumen" data-toc-modified-id="Resumen-15"><span class="toc-item-num">15&nbsp;&nbsp;</span>Resumen</a></span></li><li><span><a href="#Further-materials" data-toc-modified-id="Further-materials-16"><span class="toc-item-num">16&nbsp;&nbsp;</span>Further materials</a></span></li></ul></div>

# 🐼 **PANDAS** 🐼

![pandas](https://media.giphy.com/media/nVsLCrW5iHf6E/giphy.gif)

Mi gif favorito para la que, a partir de ahora, será tu librería favorita 😍

<a name="intro"></a>
## INTRODUCCIÓN
---

Pandas es, sin duda, la biblioteca más utilizada en el ecosistema de Python para el análisis y la manipulación de datos. Es rápida, potente, flexible, fácil de usar y de código abierto.


Entre sus principales **características** están:

* Un objeto **DataFrame** rápido y eficiente para la manipulación de datos con indexación integrada
* **Lectura y escritura** de datos en multitud de formatos: Microsoflt Excel, CSV, bases de datos SQL, JSON, diccionarios, etc
* Métodos integrados y eficientes para todo tipo de manipulación de datos: datos faltantes, subconjunto, unión, fusión, etc
* Facilidad para trabajar con datos temporales (de hecho, Pandas se llama así por "**PAN**nel **DA**ta")
* Buena **integración con otras librerías** de análisis de datos o Machine learning: scikit-learn, scipy, seaborn, plotly, etc
* Es **ampliamente utilizado** tanto en el sector privado como en el académico    


Pandas proporciona estructuras de datos de alto nivel y funciones diseñadas para hacer que el trabajo con datos estructurados o tabulares sea rápido, fácil y expresivo. Desde su aparición en ***2010***, ha ayudado a que Python sea un entorno de análisis de datos potente y productivo. Los principales objetos de pandas que se utilizarán en este libro son el DataFrame, una estructura de datos tabular orientada a columnas con etiquetas de filas y columnas, y la Serie, un objeto de matriz unidimensional etiquetado.

Pandas combina las ideas de alto rendimiento de NumPy con las capacidades flexibles de manipulación de datos de las hojas de cálculo y las bases de datos relacionales (como SQL). Proporciona una sofisticada funcionalidad de indexación para facilitar la remodelación, el corte y la división, la realización de agregaciones y la selección de subconjuntos de datos.

![image](https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fblogs-images.forbes.com%2Fgilpress%2Ffiles%2F2016%2F03%2FTime-1200x511.jpg)



Fuente: [Forbes](https://www.forbes.com/sites/gilpress/2016/03/23/data-preparation-most-time-consuming-least-enjoyable-data-science-task-survey-says/#1ba071616f63)

## Instalación

Lo primerito que deberás hacer, siempre será     
pip install pandas / conda install pandas

Esta es la manera para instalar una librería. Hay que tener en cuenta, si estamos trabajando en diferentes entornos, que las diferentes librerías no las vamos a tener instaladas a no ser que lo hagamos de manera global.

Esto es tan sencillo de corregir que no debes preocuparte de nada, los módulos se instalan muy rápido y el proceso es muy sencillo.

```python
# podemos tener la necesidad de usar o no %
# sin %
pip install <librería>

# con %
%pip install <librería>
```

Luego, una vez hemos instalado nuestra nueva librería, tenemos que importarla. Ya lo hemos visto pero...
```python
import <librería> as <alias>
```

Así vas a tener todo lo que la librería contiene. Pero también se puede importar únicamente un módulo concreto:
```python
from <librería> import <lo_que_sea>
```

In [ ]:
#pip install pandas
import pandas as pd #alias de mi librería, este pd es un estándar

In [ ]:
#pip install numpy
import numpy as np # alias estándar de la librería numpy

## **MANUAL DE PANDAS**
---

No perdáis de vista nunca el manual oficial de pandas. Es muy extenso, pero es una documentación necesaria para tener cerca toda la sintaxis.

Vais a ver que voy a ir poniendo referencias al manual en muchos apartados, pero no por ello dejéis de explorar todo el contenido. Es poco habitual tener documentaciones que son tan completas y están tan bien hechas. Aprovechadlo.

[**Vía directa a la documentación**](https://pandas.pydata.org/docs/user_guide/index.html)

## Array de Numpy

El array tiene un comportamiento muy parecdio a una lista de python.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

In [ ]:
print(f'Tamaño: {a.shape} --> 2 dimensiones de tres elementos.')          # tamaño
print(f'Cantidad de elementos en el total de las dimensiones {a.size}.')  # cantidad de elementos
print(f'Tipo de dato de los elementos: {a.dtype}.')                       # tipo de dato de los elementos
print(f'Cantidad de dimensiones: {a.ndim}.')                              # dimensiones

Pero tienen una clara ventaja cuando de hacer operaciones se trata.

In [ ]:
# declaro 2 listas
lista1, lista2 = [1, 2, 3], [4, 5, 6]

# declaro 2 array
array1, array2 = np.array([1, 2, 3]), np.array([4, 5, 6])

print(lista1)
print(array1)

* **Lista** utiliza comas para separar sus elementos. Esta estructura `[elem1, elem2, elem3]` indica que este objeto es una lista de python.
* **Array** utiliza una representación más cercana a la matemática utilizada en vectores y matrices. Su representación es sin comas, con los elementos separados por espacios `[elem1 elem2 elem3]`.

In [ ]:
# sumando las listas
lista1 + lista2

In [ ]:
# sumando array
array1 + array2

In [ ]:
# operaciones con array
multiplicacion = array1 * 2
print(f'El resultado de multiplicar array1 * 2 es: {multiplicacion}')

# operaciones con lista
multiplicacion = lista1 * 2
print(f'El resultado de multiplicar lista1 * 2 es: {multiplicacion}')

Esto facilita el trabajo cuando estamos usando conjuntos de datos y necesitamos hacer operaciones entre las diferentes columnas.

In [ ]:
# si cada array fuera una columna...
multiplicacion = array1 * array2
print(f'El resultado de multiplicar array1 * array2 = {multiplicacion}')

In [ ]:
# ¿array con diferentes tipos de dato?
variado = np.array(['Hola', 2, 3, {'municipio': 'Madrid'}])
variado

In [ ]:
variado_serie = pd.Series(variado)
variado_serie

In [ ]:
variado_serie[1]

In [ ]:
# ¿cómo accedo a "Madrid"?
variado_serie[3]['municipio']

## Introducción a las estructuras de datos de pandas
Para empezar con pandas, necesitarás sentirte cómodo con sus dos estructuras de datos de trabajo: Series y DataFrame. Aunque no son una solución universal para todos los problemas, proporcionan una base sólida y fácil de usar para la mayoría de las aplicaciones.

### 1 - Series
Una Serie es un objeto tipo array unidimensional que contiene una secuencia de valores y un array asociado de etiquetas de datos, llamado índice. Cada elemento de una Serie está indexado, lo que permite un rápido acceso a los datos. La Serie más sencilla se forma a partir de un único array de datos:

In [ ]:
serie = pd.Series(["hola",1,23,4, [1,2,3],"otro string"])

In [ ]:
serie

In [ ]:
print("Tipo de datos:")
type(serie)

La representación en cadena de una Serie mostrada interactivamente muestra el índice a la izquierda y los valores a la derecha. Como no especificamos un índice para los datos, se crea uno por defecto formado por los enteros 0 a N - 1 (donde N es la longitud de los datos). Puedes obtener la representación del array y el objeto índice de la Serie a través de sus atributos values e index, respectivamente:

In [ ]:
# una serie de pandas tiene
print("Valores:")
serie.values

In [ ]:
print("Índice:")
serie.index

In [ ]:
list(serie.values)

In [ ]:
range(5)

In [ ]:
list(range(5))

In [ ]:
list(serie.index)

Otra forma de pensar en una Serie es como un diccionario ordenado de longitud fija, ya que es un mapeo de valores de índice a valores de datos. Se puede utilizar en muchos contextos en los que se podría utilizar un diccionario.
Si tienes datos contenidos en un dict de Python, puedes crear una Serie a partir de ellos pasando el dict.

Las claves del diccionario se convertirán en los índices. Los valores en en los valores de la Serie

In [ ]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [ ]:
seriedata = pd.Series(sdata)
seriedata

In [ ]:
seriedata.info()

In [ ]:
seriedata = seriedata.astype(dtype = 'int32')

In [ ]:
seriedata.info()

In [ ]:
seriedata.index

In [ ]:
list(seriedata.index)

In [ ]:
seriedata.values

In [ ]:
list(seriedata.values)

In [ ]:
seriedata

In [ ]:
display(seriedata) #Esto es el print especial de pandas

In [ ]:
print(seriedata)

Cuando sólo se pasa un dict, el índice de la Serie resultante tendrá las claves del dict en orden. Puedes modificar el comportamientopasando las claves del dict en el orden que desee que aparezcan en la Serie resultante:

In [ ]:
estados = ['California', 'Ohio', 'Oregon', 'Texas']

In [ ]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [ ]:
serie2 = pd.Series(sdata, index=estados)

In [ ]:
serie2

In [ ]:
# otra manera de cambiar los índices es con .index()
serie.index

Me está indicando que hay índices [0, 1, 2, 3, 4, 5] y puedo cambiarlos, por ejemplo, a ['a', 'b', 'c', 'd', 'e', 'f'] muy fácilmente. Como en el ejemplo de la creación de `serie2` indicándole en un argumento qué serán los índices, o posteriormente:

In [ ]:
# serie antes del cambio
serie = pd.Series([10, 20, 30, 40, 50, 60])

In [ ]:
serie

In [ ]:
serie.index

In [ ]:
# cambio de índices
# va a pisar el RangeIndex
serie.index = ['a', 'b', 'c', 'd', 'e', 'f']

In [ ]:
# índices cambiados
serie

In [ ]:
serie.index

In [ ]:
serie2

Aquí, los tres valores encontrados en sdata se colocaron en los lugares apropiados, pero como no se encontró ningún valor para 'California', aparece como NaN (Not a Number / no es un número), lo que se considera en pandas para marcar valores perdidos o NA o NULL. Como "Utah" no se incluyó en los estados, se excluye del objeto resultante.

#### Indexación
Al ser un objeto que está indexado podemos acceder a cualquier elemento del contenedor de una manera muy fácil. Recuerda los índices objeto[índice] para ir al elemento que se encuentra en ese lugar. Recuerda los diccionarios, diccionario[key] (si es numérica sin '', si es una string debe ir entre ''). Una serie funciona del mismo modo.

Primero que todo voy a declarar una serie nueva a partir de una lista, también podría hacerlo a partir de una array, el resultado sería el mismo si la información es la misma:

In [ ]:
data = [10, 20, 30, 40, 50, 60]
serie = pd.Series(data)
serie

In [ ]:
# voy a acceder al índice 3
serie[3]

In [ ]:
# ahora con serie2 voy a acceder al índice 3...
serie2[3]

In [ ]:
# también puedo acceder de esta otra manera
serie2['Texas']

In [ ]:
# y de esta otra manera...
serie2.Texas

Pero con todo este cambio en los índices va a pasar desapercibido el nuevo dato que ha aparecido... **EL NaN**

In [ ]:
#%pip install numpy
import numpy as np

In [ ]:
print(np.nan)

In [ ]:
print('nan')

In [ ]:
# devuelve que es un float, si tenemos un NaN en una array, Python dirá que los datos que hay en ese array son float
type(np.nan)

In [ ]:
# hagamos la prueba
array = np.array([1, 2, 3, 4])

In [ ]:
array.dtype

In [ ]:
array = np.array([1, 2, np.nan, 4])

In [ ]:
array.dtype

In [ ]:
# cómo lo muestra
array

In [ ]:
# hagamos una Series con ello
serie_nan = pd.Series(array)
serie_nan

In [ ]:
# ¿será una string...?
'nan'

In [ ]:
print('nan')

In [ ]:
a = np.nan
a

In [ ]:
b = print('nan')
b

In [ ]:
a == b

In [ ]:
np.nan == 'nan'

In [ ]:
# No no puedo comprobar si a es un nan así
a == np.nan

In [ ]:
np.nan == np.nan

NaN es **incomparable**. No se puede comparar a ningún otro valor, aunque ese otro valor sea sí mismo seguirá devolviendo `False`.

### **Buscar valores NaN**
NaN significa Not A Number (No es un número) y es una de las formas habituales de representar el valor que falta en los datos. Es un valor especial de punto flotante y *no puede ser convertido a otro tipo que no sea float.*

El valor NaN es uno de los principales problemas en el análisis de datos. Es muy esencial tratar con NaN para obtener los resultados deseados.

In [ ]:
a

In [ ]:
# con numpy podemos comprobar si es nan con .isnan()
if np.isnan(a):
    print("Hola")

In [ ]:
# con pandas hacemos lo mismo con .isna()
if pd.isna(a):
  print("Hola")

In [ ]:
# ¿también sobre una serie...?

In [ ]:
# .isnan() es de numpy y tiene efecto sobre un array, pero no sobre una Serie o DataFrame
serie_nan.isnan()

In [ ]:
serie_nan.isna()

In [ ]:
serie_nan.isnull()

In [ ]:
# una pequeña forma para localizarlo rápidamente
for i, e in enumerate(serie_nan.isna()):
  if e == True:
    print(i, e)

In [ ]:
# otras formas, que descubriremos más adelante
# ¿qué me está devolviendo?
np.where(serie_nan.isna())

In [ ]:
serie_nan.loc[serie_nan.isna()].index

In [ ]:
# ¿y si le metemos algún NaN extra?
# vamos a repasarlo todo hasta aquí:
# declarar una array
# dar esa array como data para hacer una Series
# comprobamos de varias maneras (.isna(), .where(), .loc[], bucle...)

In [ ]:
array = np.array([1, 3, np.nan, 5, 6, np.nan])

In [ ]:
array

In [ ]:
print(array)

In [ ]:
display(array)

In [ ]:
serie = pd.Series(array)
serie

In [ ]:
serie.isna()

In [ ]:
np.where(serie.isna())

In [ ]:
#.isna()

In [ ]:
# .where()

In [ ]:
# .loc[]#.index

In [ ]:
# bucle (menos recomendable si el conjunto de datos es grande)

In [ ]:
# otro método de pandas para buscar NaN es pd.isnull(), que es un alias de pd.isna(). Hacen lo mismo.
pd.isnull(serie2)

In [ ]:
pd.isnull(serie).sum() #Suma de cuantos true tenemos

In [ ]:
pd.isna(serie)

In [ ]:
pd.isna(serie2).sum()

In [ ]:
# tambien, como con .isna(), puedo hacerlo sin argumentos
serie2.isnull()

In [ ]:
serie2.isnull().sum()

[Isna vs isnull](https://datascience.stackexchange.com/questions/37878/difference-between-isna-and-isnull-in-pandas)

### 2 - DataFrame

El **DataFrame** es la estructura más común y utilizada de la librería.

Hay muchas maneras de crear un DataFrame:
* Diccionario de listas (o arrays) de misma longitud.
* Series de pandas.
* Otros DataFrame.
* Cargando archivos en una gran variedad de formatos.

Pandas puede leer y escribir datos de una gran variedad de formatos. [Lee la documentación](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html)
Aunque una de las más comunes es a partir de un diccionario de listas de igual longitud o arrays NumPy:

In [ ]:
# por convención en la variable se pone el contenido, si es necesario, seguido de un df
# si tenemos los datos de una inmobiliaria:
  # inmobiliaria_df sería el nombre adecuado

# quizá estamos cotejando la relación entre el precio de venta de pisos por zonas
# y el precio de los coches vendidos por zonas
# mientras vamos explorando ambos conjuntos de datos trabajaríamos desde:
  # inmuebles_df (o casas_df)
  # vehiculos_df (o coches_df)

Primero que todo vamos a ver

In [ ]:
# Desde un diccionario
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'population': [1.5, 1.7, 3.6, 2.4, 2.9, np.nan]}

In [ ]:
df = pd.DataFrame(data) #Cargamos en un df, para ello todos los elementos tienen que tener la misma longitud

In [ ]:
# no es necesario importar, pero sí conocer sus bondades
# from IPython.display import display

In [ ]:
print(df)

In [ ]:
display(df)

In [ ]:
# es lo mismo
df

Podremos aplicar varios métodos de pandas sobre nuestros Dataframes , así como seleccionar columnas, agrupar , filtrar.....aplicar funciones calculadas por columnas.

Todo lo que podamos necesitar en nuestro día a día trabajando con datos.

In [ ]:
# otra manera de crear un df
pd.DataFrame.from_dict(data, orient="index") # orient="index"

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.from_dict.html

Si hago un dataframe a través de una lista de diccionarios:       
    - Cada diccionario será una fila   
    - Las keys serán los nombres de las columnas    
    - Tienen que tener la misma estructura

In [ ]:
pd.DataFrame.from_dict(data, orient="index") # orient="index"

In [ ]:
# Desde una lista de diccionarios
datos = [{'nombre': 'Victor',
               'apellido': 'Pablo',
               'email': 'victor.pablo@gamma.com',
               'vacaciones': 10,
               'saludo': lambda x: f'Hola {x}'} ,

         {'nombre': 'Javier',
               'apellido': 'García',
                  'email': 'javi.garcia@gamma.com',
               'vacaciones': 15,
               'saludo': lambda: print('Hola soy Javi, cuidado con los print infinitos') },
        {'nombre': 'Pablo',
               'apellido': 'Martinez',
                  'email': 'pablo.martinez@gamma.com',
               'vacaciones': np.nan,
               'saludo': lambda: print('Hola, soy Pablo y no tengo vacaciones definidas') }]

In [ ]:
# voy a acceder a la función, ¿qué pasa cuando guardo una lambda en una variable?
datos[0]['saludo']('Aitor')

In [ ]:
df_datos = pd.DataFrame(datos)

In [ ]:
display(df_datos)

Veamos algunas cosas sencillas para empezar a ver la versatilidad y facilidad de uso.

In [ ]:
df

In [ ]:
# Estoy filtrando el data frame y sobre esa columnas aplicando mean()
df['population']

In [ ]:
df[['population']]

In [ ]:
pd.DataFrame(df['population'])

In [ ]:
# df['population'].mean().round(2)
# df.population.mean().round(2)
df[['population']].mean()

Uff terrible número feo, podemos hacer un round como hacíamos en SQL por ejemplo...

In [ ]:
#Redondeamos la media
df['population'].mean().round(2)

Al llamar a ```df['pop']``` lo que estoy haciendo es decirle que de todo mi data frame, me haga un *slicing* sólo de la columna pop. Os suena familiar verdad?

In [ ]:
df

In [ ]:
df.columns

In [ ]:
for col in df.columns:
  print(f'Columna {col} \n')
  display(df[col]) # mostrar diferencias
  print('-'*10)

In [ ]:
# Para visualizar un dataframe utilizaremos display y NO print
print(df)

In [ ]:
df

In [ ]:
lista = [1.5, 1.7, 3.6, 2.4, 2.9] #Los NaN no entran en el cálculo, los omite

In [ ]:
sum(lista)/len(lista)

In [ ]:
suma = 0
for i in df['population']:
  suma+=i
  print(f'i {i} \t suma {suma}')

In [ ]:
df

Como estamos usando Collab, los objetos DataFrame de pandas se mostrarán como una tabla HTML más amigable para el navegador.

Os dejo el enlace a la docu de pandas para que veáis todos los metodos de cargar/guardar ficheros en pandas --> [📚](https://pandas.pydata.org/docs/reference/io.html)

In [ ]:
# Crear df a partir de listas
lista1 = ['col1', 'col2', 'col3']
lista2 = [1, 2, 3]
lista3 = [2, 3, 4]
lista4 = [3, 4, 5]

pd.DataFrame([lista2, lista3, lista4], columns = lista1)

#### Cargamos datos de formato CSV

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/gamma/Data/00. Data/avocado.csv') # MI VARIABLE SE LLAMA DF
#nota mental index_col

In [ ]:
# por si llegado el momento es necesario
# df_intacto = df.copy()

In [ ]:
df.drop(columns = 'Unnamed: 0', axis = 1, inplace = True)

In [ ]:
df

##### Visualizamos tamaño

In [ ]:
df.shape

In [ ]:
df.shape[0] #Filas

In [ ]:
df.shape[1] #Columnas

#### Cargamos datos de formato xlsx

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# para ver archivos en este formato hay que hacer una instalación previa

In [ ]:
#pip install openpyxl

In [ ]:
retail = pd.read_excel('/content/drive/MyDrive/gamma/Data/00. Data/Online Retail.xlsx')

In [ ]:
retail.shape

In [ ]:
retail

##### Visualizamos las primeras filas

In [ ]:
df.head()

Por defecto head me muestra las 5 primeras filas, puedo ver algunas más o algunas menos pasándole un número como argumento

In [ ]:
df.head(20)

##### Visualizamos las últimas filas

In [ ]:
df.tail()

Excatamente igual que con .head() le pasamos un argumento a .tail()

In [ ]:
df.tail(3)

##### Visualizamos una muestra aleatoria

In [ ]:
retail.sample(5) #si no le pasamos un argumento, visualiza una sola fila de forma aleatoria.

In [ ]:
# Muestra aleatoria de 5 filas
df.sample(5)

In [ ]:
df.sample(frac=0.01) # Muestra aleatoria del 1%

In [ ]:
df[['AveragePrice', 'type', 'year', 'region']].sample(5)

In [ ]:
df_sample = df[['AveragePrice', 'type', 'year', 'region']].sample(5)

In [ ]:
df_sample

In [ ]:
#pd.set_option('display.max_rows', 20)

In [ ]:
guardo_sample = retail.sample(frac=0.1)

In [ ]:
guardo_sample.head(3)

In [ ]:
guardo_sample.shape

## Preparando **Análisis Exploratorio de Datos (EDA)**

Hay que tener claro cómo se distribuyen y cómo son nuestros datos. Una vez tenemos la información cargada empieza su exploración:
* Vista preliminar: tamaño, vistas preliminares...
* Estructura: qué tipo de dato contiene cada columna
* Resumen estadístico: nos proporcionará información muy útil y rápida para las variables numéricas como el máximo, el mínimo, la media, la mediana...
* Exploración de valores faltantes
* Exploración de variables categóricas
* Distribución de los datos

Una vez tenemos conocimiento sobre la estructura, distribución y comportamiento de nuestros datos empezará la toma de decisiones sobre qué hacer con los datos faltantes, en caso de haberlos.

In [ ]:
df

In [ ]:
# primeras filas
df.head(3)

In [ ]:
# ultimas filas
df.tail(3)

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
# NaN por columna
df.isnull().sum()

In [ ]:
retail.info()

In [ ]:
retail.isnull().sum()

In [ ]:
# resumen estadístico
df.describe() #Solo lo hace con columnas que tienen datos de tipo numerico

In [ ]:
df.describe().T

In [ ]:
type(df.describe())

In [ ]:
df.max()

In [ ]:
df.mean()

In [ ]:
df.mean(numeric_only=True) # numeric_only=True

### Referenciar a columnas concretas
Hay varias posibilidades:
1. `df.columna` que es exactamente lo mismo que `df['columna']`
  * Estas dos son las maneras más usadas. Por ello normalmente normalizamos las columnas eliminando mayúsculas y espacios (con espacios la primera opción no se puede usar).
2. `df[['columna']]` el uso del doble corchete devolverá un DataFrame.

In [ ]:
# data['columna']
# quiero la media únicamente la media de AveragePrice
df['AveragePrice'].mean().round(2)

In [ ]:
# data.columna
# cuidado con esto, porque si el nombre de la columna contiene espacios no podéis usar esta sintaxis para llamar a una columna
df.AveragePrice.mean().round(4)

In [ ]:
df['Total Bags'].mean().round(4)

In [ ]:
df.Total Bags.mean()

In [ ]:
nombre = 'Total Bags'

In [ ]:
# si quiero quitar la variable de la memoria ram
del nombre

#### Normalización de columnas

In [ ]:
df.columns

In [ ]:
#Mini reto
#Vamos a normalizar el nombre de las columnas del df
df.columns = df.columns.str.lower().str.replace(' ','_')

In [ ]:
df

In [ ]:
df["total_volume"].mean()

In [ ]:
df["total_volume"].min()

In [ ]:
df["total_volume"].max()

In [ ]:
df["total_volume"].std()

In [ ]:
df.total_volume.std()

In [ ]:
df['type'].value_counts()

In [ ]:
df.year.value_counts()

In [ ]:
df.region.value_counts()

In [ ]:
df.large_bags.head(20)

In [ ]:
df['large_bags'].value_counts() #Con las continuas no me da mucha info

In [ ]:
# Seleccionamos las columnas cuyo tipo de dato es int64
columnas_numericas = df._get_numeric_data()

In [ ]:
columnas_numericas

In [ ]:
df.dtypes #tipo de dato que contiene cada columna

In [ ]:
# Podemos incluir y excluir
df.select_dtypes(include="object").head()

In [ ]:
df.select_dtypes(include="float").head()

In [ ]:
df.select_dtypes(exclude = 'object').head()

In [ ]:
df.sample()

## Operaciones básicas con los dataframes

### Seleccionamos una columna

In [ ]:
df.columns #Podemos ver las columnas del df

In [ ]:
df.columns.tolist() #Sacar listado de las columnas del df

In [ ]:
df.columns.to_list()

In [ ]:
# Usando df.columna / df['columna'] obtengo una Serie
unacolumna = df["total_bags"]
unacolumna

In [ ]:
# Usando df[['columna']] obtengo un DataFrame
unacolumna_dataframe = df[["total_bags"]]
unacolumna_dataframe.head()

In [ ]:
# Si a pesar de pasarle una lista, solo tiene un elemento, tengo un DataFrame con una sola columna

In [ ]:
# O dos :), o las que queramos

### Seleccionamos varias columnas

In [ ]:
df.columns

In [ ]:
df_varias_columnas = df[["total_bags", "averageprice", "region"]]

In [ ]:
df_varias_columnas.sample(10)

In [ ]:
#le podemos pasar directamente una lista con los nombres de las columnas
lista_columnas = ['total_bags', 'small_bags', 'large_bags', 'xlarge_bags']

In [ ]:
# sintaxis para seleccionar columna: df[columna]
# si van a ser varias columnas: columna será la lista de strings o la variable en la que se haya declarado la lista
# df[lista] --> df[['col', 'col', 'col', 'col']]

In [ ]:
df_nuevo = df[lista_columnas]
# df_nuevo = df[['total_bags', 'small_bags', 'large_bags', 'xlarge_bags']]

In [ ]:
df_nuevo.sample()

In [ ]:
# Listar los nombres de columnas de un DataFrame
columnas = list(df.columns)
columnas

In [ ]:
copia = df.copy() # Hacemos una copia

In [ ]:
copia

In [ ]:
copia.drop(columns= 'averageprice')

In [ ]:
copia

In [ ]:
copia.drop(columns="averageprice",inplace=True) #Por defecto inplace = False
copia.columns

In [ ]:
copia

In [ ]:
df.head(1) # Las modificaciones que hago en la copia son independientes del original y no afectan

In [ ]:
df_nuevo

In [ ]:
df_nuevo.drop(columns = 'total_bags', inplace = True)

In [ ]:
df

In [ ]:
df_nuevo is df

In [ ]:
copia is df# PORQUE COPIA NO ES DF

## 🚨🚨🚨 ¡¡OJO CUIDADO!!🚨🚨🚨

In [ ]:
copia2 = df # si igualo la variable sin hacer copy me cargo el original

In [ ]:
copia2.drop(columns="total_bags", inplace=True)

In [ ]:
copia2.columns

In [ ]:
copia2 is df # PORQUE COPIA2 SÍ ES DFdf.

In [ ]:
df.head()

### Obtener los valores únicos de una columna (es decir, una serie)

In [ ]:
df.region.unique()

In [ ]:
list(df.region.unique())

In [ ]:
df_datos.nombre.unique()

In [ ]:
len(list(df.region.unique()))

In [ ]:
df.region.nunique()

In [ ]:
df_datos.nombre.unique()

### Cambiar el tipo de datos de una columna

In [ ]:
df['averageprice'].dtype == 'float16'

In [ ]:
df.averageprice

**RECORDATORIO**

El tipo de dato afecta directamente a la cantidad de memoria necesaria para almacenar la información. Modificar el tipo de dato asignado puede ser crucial para las diferentes operaciones que tengamos que realizar (que las fechas se reconozcan como fecha, si con int16 es suficiente no tener int64 asignado...)

A esto se le llama **pelar** los datos.

In [ ]:
def pelar(df):
  for col in df.columns:
    if df[col].dtype == 'float64':
      df[col] = df[col].astype('float16')
  return df

In [ ]:
pelar(df)
df.dtypes

In [ ]:
df.info()

In [ ]:
df.averageprice.head(10)

In [ ]:
df.averageprice.astype(dtype="int8")

In [ ]:
df.averageprice.head()

In [ ]:
df.info()

In [ ]:
# Atención!! que no se cambian los datos si no sobreescribimos la columna
df.averageprice = df.averageprice.astype(dtype='float16')

In [ ]:
df.averageprice.head()

In [ ]:
df.info()

In [ ]:
df.columns

In [ ]:
df["BolsaXL"] = df["large_bags"].astype(dtype='float32') #Puedo crear o reasignar columnas

In [ ]:
df.head()

In [ ]:
# Para crear una columna nueva solamente tengo que darle un nombre, por ejemplo df["nueva"]
# Como cuando en un diccionario añado una KEY

In [ ]:
df["otra"] = df["small_bags"] * df["total_volume"]

In [ ]:
df_copia = copia
df_copia

In [ ]:
df.sample(10)

In [ ]:
df_copia['otra'] = df['small_bags'] * df['total_volume']

In [ ]:
df_copia.head(3)

In [ ]:
# No puedo operar strings y números
df["ejemplo"] = df.averageprice * df.region

In [ ]:
df.averageprice = df.averageprice.astype(dtype = 'int')
df.averageprice.head(2)

In [ ]:
df["ejemplo"] = df.averageprice * df.region

In [ ]:
df[['ejemplo']].sample(5)

In [ ]:
df[["AveragePrice","region","ejemplo"]].sample(15)

In [ ]:
df.ejemplo.isna().sum()

### Filtramos los datos por el valor de las columnas

In [ ]:
df.region.nunique() #Sacamos el numero de valores unicos

In [ ]:
len(df.region.unique())

In [ ]:
df['region']

In [ ]:
df2 = df[df["region"] == "Houston"]

In [ ]:
df2

In [ ]:
df2.region.value_counts()

In [ ]:
df2.region.unique()

In [ ]:
df2 = df[df["region"] != "Houston"]

In [ ]:
df[df.region != 'Houston'][['region', 'small_bags']]

In [ ]:
df2.sample(4)

In [ ]:
df2.region.unique()

In [ ]:
df.info()

In [ ]:
# multicondición, & and lógico
multi = df[(df.region == "Houston") & (df.year == 2015)]

In [ ]:
multi.head(3)

In [ ]:
multi = df[(df.region == "Houston") | (df.year == 2015)][['region', 'small_bags', 'year']]

In [ ]:
multi.head(3)

Podemos exportar estos df en cualquier momento a varios formatos. Por ejemplo a CSV:

In [ ]:
multi.to_csv('/content/drive/MyDrive/gamma/Data/00. Data/avocado_infinitos.csv') #to_csv lo export a fichero csv y le paso como argumento la ruta y el nombre

In [ ]:
multi_p = df[(df.region == "Houston") | (df.region == "Albany")] #OR

In [ ]:
multi_p.region.unique()

In [ ]:
# | or logico
df[(df.region=="Houston") & (df.averageprice >= 1) & (df.year != 2017)].head(8)

In [ ]:
# esto es region houston Y precio >= 1, o año 2017
df[(df.region=="Houston") & (df.averageprice >= 1) | (df.year == 2017)].head(8)

In [ ]:
# esto es region houston y, únicamente viendo houston, que el precio sea tal o el año sea cual
df[(df.region=="Houston") & ((df.averageprice >= 1) & (df.year != 2017))].head(8)

### Copia de un dataframe y renombrar columnas

In [ ]:
otracopia = df.copy()

#### Renombramos columnas
Para renombrar columnas necesitamos un diccionario

In [ ]:
# cuidado con los cambios realizados
# usar df.copy()

In [ ]:
# se puede hacer directamente
df_renombrado = df.copy()
# df_renombrado.columns = df.columns.str.lower().str.replace(' ','_')

In [ ]:
columnas = df_renombrado.columns #Nombres originales

In [ ]:
# se puede hacer con un diccionario
diccio_nuevas = {columna: columna.replace(" ", "_").lower() for columna in columnas}

In [ ]:
diccio_nuevas

In [ ]:
diccio_nuevas['AveragePrice'] = 'average_price' #Reasigno el value del diccionario
diccio_nuevas

In [ ]:
# aquí estoy pisando la variable en la que tengo almacenado el DataFrame
df_renombrado = df_renombrado.rename(columns=diccio_nuevas)
df_renombrado.sample(5)

In [ ]:
# Utilizamos el inplace=True para que se ejecute la acción sobre el DataFrame
df_renombrado.rename(columns=diccio_nuevas)

In [ ]:
df_renombrado.rename(columns = diccio_nuevas, inplace = True)

El método rename me permite renombrar solamente las columnas que yo quiera, las que estén en el diccionario que me he hecho. No hace falta renombrar todas a la vez

In [ ]:
#Hacemos otro diccionario
otro = {"unnamed:_0": "Inútil","date":"fecha", "columna que no existe ni de broma": "no hace nada"}

In [ ]:
df_renombrado.columns

In [ ]:
#Uso el dicc que me acabo de hacer para renombrar las columnas
df_renombrado.rename(columns = otro, inplace=True)

In [ ]:
df_renombrado.columns #Miramos a ver como han quedado las columnas

Las columnas que estaban mapeadas en mi diccionario, se renombran.

Las que no estaban:


1.   Porque existen en mi df pero no estaban en el diccionario.
2.   Porque existen en el diccionario pero no en mi df.

no se modificarán.

In [ ]:
df_renombrado.drop(columns="Inútil", inplace = True) #Me tricoto la columna 'Inútil'

In [ ]:
df_renombrado

In [ ]:
df.head()

### Podemos renombrar las columnas machacando el atributo columns

Requiere una lista con el mismo número de elementos que de columnas en el df.

Pisamos la lista de los nombres de las columnas por una de nuestro gusto.

In [ ]:
# Vamos a hacer una copia para no cargarnos más df
df_columnas = df.copy()

In [ ]:
#Columnas ahora mismo en mi copia
df_columnas.columns

In [ ]:
len(df_columnas.columns) #Tengo 13 columnas

In [ ]:
prueba = ["🐼"]*14

In [ ]:
#Listado nuevo de nombres de columnas
prueba

In [ ]:
df_columnas.columns = prueba

In [ ]:
df_columnas.head()

In [ ]:
prueba_2 = prueba = ["👍"]*14
df_columnas.columns = prueba_2

In [ ]:
df_columnas

He machacado ese traibuto columnas en mi df3. Funcionando!

La longitud de ambos elementos debe ser la misma, sino fallará.

### Borramos columnas / filas

In [ ]:
df.head(1)

In [ ]:
df.head(10)

#### Puede ser que porque es una columna que esté demasiado sucia, o por no necesidad para el estudio, o porque la he usado para hacer una nueva columna cálculada y ya no la necesito o por el motivo que me de la gana, quiero eliminar una columna. ¿Como lo hago?

In [ ]:
df.columns

In [ ]:
df_copia = df.copy()

In [ ]:
df_copia.drop(labels = ['4046','4225'],axis = 1) #Axis 1 --> Columnas

In [ ]:
df_copia.head(1) #Sigo teniendo lo que he dropeado, porque el famoso inplace

In [ ]:
df_copia.drop(labels = ['4046','4225'],axis = 1, inplace = True) # inplace para guardar estos cambios en el DF

In [ ]:
df_copia.head(1)

In [ ]:
df_copia.head(10)

In [ ]:
#filas
df_copia.drop([0,1,4],axis = 0, inplace = True) #puedo no pasarle labels, lo entiende por posicion

In [ ]:
df_copia.head(10)

En vez de darle los axis en los que lo quiero hacer, puedo ponérselo fácil y decirle si lo que le paso son columnas o índices.

In [ ]:
df_copia.drop(columns = ["4046","4225","4770"]) #Ojo pandas que el listado que te paso corresponde con columnas

In [ ]:
# ya había eliminado estas columnas así que lanza error
df_copia = df.copy()
df_copia.drop(columns = ["4046","4225","4770"])

In [ ]:
df_copia

In [ ]:
# para guardaarlo INPLACE
df_copia.drop(columns = ["4046","4225","4770"], inplace = True)

In [ ]:
df_copia.head(1)

In [ ]:
df_copia.head(5)

In [ ]:
df_copia.head(5)

In [ ]:
df_copia.drop(index = [0,1,3]) #Ojo que lo te paso son índices --> afecta a únicamente aquellos índices que son idénticos

Las filas también se pueden eliminar, pero tenemos que tener en cuenta que los índices no se reinician. El índice se asocia a la fila, no al orden.

### Reset_index y set_index

[Documentación](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.reset_index.html) completa de estos métodos de pandas.

In [ ]:
df_copia.drop(index = [x for x in range(10)]) #Me cargo los índices del 0 al 9

In [ ]:
df_copia.head(10)

In [ ]:
df_copia.drop(index = [x for x in range(10)], inplace = True)

In [ ]:
df_copia.head(2)

In [ ]:
df_copia.reset_index()

Me ha creado un nuevo index y lo que tenía antes me lo ha dejado como primera columna

In [ ]:
df_copia.head(10)

Mentira, no me ha hecho nada. Adivinas por que?

In [ ]:
df_copia.reset_index(inplace = True)
df_copia.head(10)

Ahora sí que han quedados grabados los cambios. Me ha creado un nuevo index que si que tiene valores únicos y todos consecutivos desde el 0, y la columna que tenía antes como índice la ha metido en la columnas de mi df ( la primera columna ).

Hay ocasiones en las que esta columna que era el índice no la necesito para nada, por lo que nos la podemos dropear a posteriori o podemos con un argumento decirle a pandas que se desprenda de esa columna y no la meta en el df.

In [ ]:
#Pongo el df en su estado original para volver a resetear el indice pero esta vez diciéndole que no queremos la columna de indice que teníamos antes
df_copia.drop(columns='index', inplace = True) #Quitamos la columna que nos generó el primer reset_index
df_copia.drop(index= [1,2,5,6], inplace = True)
df_copia.head(10)

In [ ]:
df_copia.reset_index(drop = True, inplace = True) # drop = True es para que no me genere la nueva columna index
df_copia.head(10)

In [ ]:
# puedo hacer borrado de filas enteras y columnas enteras todo a la vez
df_copia.drop(index = [0, 1, 2], columns = ['fecha', 'year'])

In [ ]:
df_copia.reset_index() # Me mete lo que era el indice original como nueva columna

#### SET_INDEX

Aquí no reiniciamos el índice, si no que le decimos qué tiene que usar como índice.

No tiene porque ser una columna automática, y aun menos una columna que tenga que ser numérica.

In [ ]:
df_date = df.copy()
df_date = df_date.set_index("fecha") #Le digo que columna pasa a servir de indice en mi df
df_date.head()

¿Para qué nos puede servir tener la fecha como índice?    
Para analizar series temporales,ver como varía algo con el tiempo, pero os avanzo un poco de fantasía 🌈

In [ ]:
#%pip install seaborn
import seaborn as sns #Librería de visualización y su AKA correspondiente
sns.set_context("poster")
sns.set(rc={'figure.figsize': (20.,6.)})
sns.set_style('whitegrid')

In [ ]:
df_filtro = df_date[df_date.region == "Albany"]
df_filtro.head(5)

In [ ]:
len(df_filtro.index)

In [ ]:
df_filtro.index.nunique() #Cuantas fechas distintas tengo en mi índice

In [ ]:
prueba = df_filtro.loc[~df_filtro.index.duplicated(), :] #virgulilla, sirve para negar

In [ ]:
prueba

In [ ]:
prueba.index.has_duplicates

In [ ]:
df.fecha.duplicated().sum()

In [ ]:
plot = sns.barplot(data=prueba, x=prueba.index, y=prueba.small_bags, color="red", label="small_bags")
plot.set_xticklabels(plot.get_xticklabels(), rotation=90)
plot

In [ ]:
df.index.is_unique

# HASTA AQUÍ !!!!
![aquí nos hemos quedado](https://media.tenor.com/ZzhRs6kpGGMAAAAC/you-shall-not-pass-gandalf.gif)

In [ ]:
# recarga de datos

# librerías
# import pandas as pd
# import numpy as np

# DF original
# df = pd.read_csv('/content/drive/MyDrive/gamma/Data/00. Data/avocado.csv')

# transformaciones hechas hasta borramos columnas
# columnas = df.columns
# diccio_nuevas = {columna: columna.replace(" ", "_").lower() for columna in columnas}
# diccio_nuevas['AveragePrice'] = 'average_price'
# diccio_nuevas['Unnamed: 0'] = "inútil"
# diccio_nuevas['Date'] = 'fecha'

# aplicar transformaciones
# df.rename(columns = diccio_nuevas, inplace = True)
# df.drop(columns="inútil", inplace = True)

# export a CSV
# df.to_csv('/content/drive/MyDrive/gamma/Data/00. Data/avocado_hasta_borramos_col-fila_v4.csv', index = False)

# conectar con Drive
# from google.colab import drive
# drive.mount('/content/drive')

# cargar el CSV
df = pd.read_csv('/content/drive/MyDrive/gamma/Data/00. Data/avocado_hasta_borramos_col-fila_v4.csv')

### Apply

Aplica una función a lo largo de un eje del DataFrame -->[DOCU](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html)

In [ ]:
df.head(2)

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany

In [ ]:
#Creamos una función sencilla que vamos a aplicar
def euros(x):
    return f"{x}€"

In [ ]:
euros(5)

'5€'

In [ ]:
lista = [135,14.16,164.62,23.15,26.15]

#### **`map()`**
La función **`map()`** nos va a facilitar hacer bucles constantemente. Permite aplicar una **función** a cada uno de los elementos de una lista, o cualquier otra estructura que sea iterable (lista, set, tupla...). Ahora que estamos conociendo la librería pandas y vamos a estar manejándonos con **`Series`** y con **`DataFrame`** vamos a ver su gran utilidad.

Hay que tener en cuenta que una `Series` es una columna y su comportamiento es similar al de una lista. **`map()`** va a facilitarnos el trabajo de transformación de datos, si hay que hacer una modificación para toda una columna (o varias) a través de una función.

**Ejemplo**
```python
# Definimos una función que calcula el cuadrado de un número
def cuadrado(numero):
    return numero ** 2

# Tenemos una lista de números
numeros = [1, 2, 3, 4, 5]

# Usamos map() para aplicar la función cuadrado a cada elemento de numeros
# casteamos para que el resultado sea una lista
resultados = list(map(cuadrado, numeros))

print(resultados)
```
La salida de este print será `[1, 4, 9, 16, 25]`. Sin hacer un bucle se ha llamado a la función aplicándola para cada uno de los elementos que hay en la lista.

In [ ]:
nuevalista = list(map(euros,lista)) #map() puede evitarnos bucles tediosos
nuevalista

['135€', '14.16€', '164.62€', '23.15€', '26.15€']

**`map()`** puede facilitarnos mucho la vida para hacer transformaciones, o preparaciones de datos. Es una de las alternativas eficientes que hay para hacer estas modificaciones. En la siguiente celda de código vamos a ver un ejemplo para convertir una variable categórica, con nuestros amigos aguacates, que pase de string a int. En la columna `type` hay información sobre dos posibles tipos de aguacates: `'conventional'` y `'organic'`. Puede ser útil tener esta variable categórica en formato numérico. Por no perder información lo que vamos a hacer es:
1. Crear un diccionario que sirva para mapear. El funcionamiento es el siguiente:
  * el diccionario es par de valores `key:value`
  * el `key` es el valor que encuentra (`'conventional'` u `'organic'`)
  * el `value` es el valor que va a poner en caso de encontrar uno u otro (1 ó 2)
1. Añadir una columna `type_numeric` en la que tengamos el tipo de aguacate en formato numérico. En esta columna debe haber información numérica, para `'conventional'` que sea **1** y para `'organic'` que sea **2**.

In [ ]:
# confirmación que en type hay únicamente esos dos valores
df.type.unique()

array(['conventional', 'organic'], dtype=object)

In [ ]:
# diccionario para los nuevos valores
dic_mapeo = {
            'conventional': 1,
            'organic': 2
            }

In [ ]:
# creación nueva columna
# crea la columna 'type_numeric'
# con la información de la columna 'type'
# donde encuentres la key, pon el value de lo que hay en el diccionario
df['type_numeric'] = df['type'].map(dic_mapeo)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18249 entries, 0 to 18248
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fecha          18249 non-null  object
 1   average_price  18249 non-null  float64
 2   total_volume   18249 non-null  float64
 3   4046           18249 non-null  float64
 4   4225           18249 non-null  float64
 5   4770           18249 non-null  float64
 6   total_bags     18249 non-null  float64
 7   small_bags     18249 non-null  float64
 8   large_bags     18249 non-null  float64
 9   xlarge_bags    18249 non-null  float64
 10  type           18249 non-null  object
 11  year           18249 non-null  int64
 12  region         18249 non-null  object
 13  type_numeric   18249 non-null  int64
dtypes: float64(9), int64(2), object(3)
memory usage: 1.9+ MB

In [ ]:
df.head(2)

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region,type_numeric
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,1
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,1

La nueva columna creada es `int64` y es demasiado para tener únicamente valores que pueden ser 1 ó 2. Hay que cambiarlo a int8...

In [ ]:
df.astype({'type':'category', # al ser variable categórica
           'type_numeric':'int8', # esto podría ser cambien con un type category
                                  # quizá nos interese tenerlo como dato numérico, si no siempre se puede cambiar...
           'fecha':'datetime64',
           'year':'int16'
          }).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18249 entries, 0 to 18248
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fecha          18249 non-null  datetime64[ns]
 1   average_price  18249 non-null  float64
 2   total_volume   18249 non-null  float64
 3   4046           18249 non-null  float64
 4   4225           18249 non-null  float64
 5   4770           18249 non-null  float64
 6   total_bags     18249 non-null  float64
 7   small_bags     18249 non-null  float64
 8   large_bags     18249 non-null  float64
 9   xlarge_bags    18249 non-null  float64
 10  type           18249 non-null  category
 11  year           18249 non-null  int16
 12  region         18249 non-null  object
 13  type_numeric   18249 non-null  int8
dtypes: category(1), datetime64[ns](1), float64(9), int16(1), int8(1), object(1)
memory usage: 1.6+ MB

In [ ]:
# recuerda: .astype() no tiene inplace. Para que se queden guardados los cambios:
  # si lo haces sobre una columna debes pisar la columna
  # si lo haces sobre varias columnas usa el diccionario y debes pisar el DataFrame
df = df.astype({'type':'category',
           'type_numeric':'int8',
           'fecha':'datetime64',
           'year':'int16'
          })

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18249 entries, 0 to 18248
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fecha          18249 non-null  datetime64[ns]
 1   average_price  18249 non-null  float64
 2   total_volume   18249 non-null  float64
 3   4046           18249 non-null  float64
 4   4225           18249 non-null  float64
 5   4770           18249 non-null  float64
 6   total_bags     18249 non-null  float64
 7   small_bags     18249 non-null  float64
 8   large_bags     18249 non-null  float64
 9   xlarge_bags    18249 non-null  float64
 10  type           18249 non-null  category
 11  year           18249 non-null  int16
 12  region         18249 non-null  object
 13  type_numeric   18249 non-null  int8
dtypes: category(1), datetime64[ns](1), float64(9), int16(1), int8(1), object(1)
memory usage: 1.6+ MB

In [ ]:
df.head(2)

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region,type_numeric
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,1
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,1

### Apply
Va a hacer una cosa parecida a lo que hace map. Se le pasa una función y va a iterar por toda la columna para aplicarla. En este ejemplo, por no alterar más nuestro DataFrame, se crea una nueva columna `'avg_price_euros'` que se va a rellenar con la información que hay en la columna ya existente `'average_price'`. Al usar `.apply()` automáticamente y sin necesidad de un bucle que recorra toda la `Serie` va a aplicar la función sobre el valor de cada fila a lo largo de esa columna.

In [ ]:
# Aplicamos la función a una columna y vemos el resultado en la salida
df['avg_price_euros'] = df.average_price.apply(euros)
df.head(3)

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region,type_numeric,avg_price_euros
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,1,1.33€
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,1,1.35€
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,1,0.93€

In [ ]:
# Hazlo con lambda!!
# Vamos a hacer una columna nueva que junte región y año solamente si en type pone convencional y si no otra cosa

In [ ]:
df["fantasya"] = df.apply(lambda fila: f"{fila['year']}, {fila['region']}" \
                          if fila["type"] == "conventional" \
                          else "OTRACOSA", axis=1)

                          #aquí le digo escribe una string año, region
                          #si en la columna type para esta fila el valor es conventional HAZ ESA INSTRUCCION
                          #PARA TODO LO DEMAS escribe OTRACOSA

In [ ]:
df[df.type == 'conventional'].sample(2)

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region,type_numeric,avg_price_euros,fantasya
1037,2015-01-18,1.14,149319.82,2910.77,103890.90,2048.78,40469.37,22405.47,17913.92,149.98,conventional,2015,Indianapolis,1,1.14€,"2015, Indianapolis"
4121,2016-09-25,1.37,2568161.45,748452.52,947415.59,73332.83,798960.51,698140.82,100819.69,0.00,conventional,2016,Midsouth,1,1.37€,"2016, Midsouth"

In [ ]:
df[df.type == 'organic'].sample(2)

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region,type_numeric,avg_price_euros,fantasya
13498,2016-11-20,1.81,9539.41,20.66,244.29,0.00,9274.46,9274.46,0.00,0.0,organic,2016,NorthernNewEngland,2,1.81€,OTRACOSA
15426,2017-01-22,0.98,29282.55,12519.74,5289.45,11.43,11461.93,8840.51,2621.42,0.0,organic,2017,Denver,2,0.98€,OTRACOSA

In [ ]:
# modifico un poco, me interesa más que si no se cumple la condición de convencional salga un NaN

In [ ]:
import numpy as np
df["fantasya"] = df.apply(lambda fila: f"{fila['year']}, {fila['region']}" \
                          if fila["type"] == "conventional" \
                          else np.nan, axis = 1)

In [ ]:
df.sample(5)

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region,type_numeric,avg_price_euros,fantasya
15795,2017-02-05,1.35,3551.43,568.01,1410.33,0.00,1573.09,959.37,613.72,0.00,organic,2017,Indianapolis,2,1.35€,NaN
4523,2016-01-03,1.19,421093.02,13858.25,309377.59,918.32,96938.86,89684.36,7254.50,0.00,conventional,2016,Philadelphia,1,1.19€,"2016, Philadelphia"
4911,2016-07-17,1.31,471698.22,150251.55,237468.05,16900.69,67077.93,67069.07,8.86,0.00,conventional,2016,Sacramento,1,1.31€,"2016, Sacramento"
1381,2015-06-07,0.96,189470.19,128293.70,10385.79,10508.18,40282.52,31059.24,8944.38,278.90,conventional,2015,Nashville,1,0.96€,"2015, Nashville"
7737,2017-12-24,1.14,469533.33,128124.60,287781.13,989.68,52637.92,46568.56,579.63,5489.73,conventional,2017,Sacramento,1,1.14€,"2017, Sacramento"

In [ ]:
# ahora creamos una columna nueva que se llama prueba
# tiene que escribir 'loquesea', si en esa fila en la columna region pone 'Albany'
# si pone cualquier otra cosa lo que debe escribir es lo que haya en esa fila en la columna euros

In [ ]:
df["prueba"] = df.apply(lambda palabra: "loquesea" \
                        if palabra["region"] == "Albany" \
                        else palabra["avg_price_euros"], axis=1)

In [ ]:
# comprobamos para los registros que en region pone 'Albany'
df[df['region'] == "Albany"].head(3)

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region,type_numeric,avg_price_euros,fantasya,prueba
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,1,1.33€,"2015, Albany",loquesea
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,1,1.35€,"2015, Albany",loquesea
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,1,0.93€,"2015, Albany",loquesea

In [ ]:
# comprobamos para los registros que en region pone cualquier cosa que no sea 'Albany'
df[df['region'] != "Albany"].sample(8)

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region,type_numeric,avg_price_euros,fantasya,prueba
1678,2015-09-20,1.25,361361.60,14832.84,251090.34,580.30,94858.12,84698.03,10160.09,0.0,conventional,2015,Philadelphia,1,1.25€,"2015, Philadelphia",1.25€
17707,2018-01-14,1.79,44955.89,133.39,31177.44,0.00,13645.06,13635.06,10.00,0.0,organic,2018,Chicago,2,1.79€,NaN,1.79€
4882,2016-02-07,0.91,198011.31,60920.14,79535.27,179.28,57376.62,53859.35,3517.27,0.0,conventional,2016,Roanoke,1,0.91€,"2016, Roanoke",0.91€
9629,2015-04-26,1.36,16289.60,256.76,13336.25,0.00,2696.59,563.33,2133.26,0.0,organic,2015,CincinnatiDayton,2,1.36€,NaN,1.36€
13274,2016-03-13,1.40,91287.93,3388.40,46780.43,2001.92,39117.18,21173.39,17943.79,0.0,organic,2016,Midsouth,2,1.4€,NaN,1.4€
18016,2018-02-04,1.40,11077.99,1053.22,25.24,0.00,9999.53,9999.53,0.00,0.0,organic,2018,Pittsburgh,2,1.4€,NaN,1.4€
5133,2016-04-10,0.96,397990.96,158605.28,126384.55,6056.81,106944.32,57960.91,48983.41,0.0,conventional,2016,SouthCarolina,1,0.96€,"2016, SouthCarolina",0.96€
5539,2016-06-19,0.86,6964845.92,2805282.99,1600273.86,140268.18,2419020.89,1643598.70,767883.69,7538.5,conventional,2016,West,1,0.86€,"2016, West",0.86€

In [ ]:
# voy a dejar el DataFrame como estaba al principio de esta sección...
df.drop(columns=['type_numeric', 'avg_price_euros', "fantasya", "prueba"], inplace=True)

In [ ]:
df.head(1)

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany

In [ ]:
# Aplicamos una función que además de x tiene otro argumento.

Recordatorio de cómo era la función euros
```python
def euros(x):
    return f"{x}€"
```
Al aplicarla sobre una `Serie` con el método `.apply()` el valor que hay en cada una de las filas va a ser `x`, va a ser el argumento que va a entrar con el que la función va a realizar los cambios que tiene que hacer.

A ver qué pasa si yo a una función le digo ahora que si el valor de la fila empieza por 'a' devuelva el valor que hay, y en caso contrario devuelva una palabra que le tengo que pasar como argumento...

In [ ]:
def empiezapora(palabra,x):
    if x.lower().startswith("n"):
        return x
    else:
        return palabra

In [ ]:
# si gente empieza por a devuelve gente
# no empieza por a, devuelve la palabra que se le pasa en primer argumento

In [ ]:
empiezapora("hola", "gente")

'hola'

In [ ]:
# si alegría empieza por a devuelve alegría
# en caso contrario devuelve la palabra que tenga en el primer argumento

In [ ]:
empiezapora("hola", "Alegría")

'Alegría'

Como he hecho con la función euros, le digo que aplique esta función por cada fila que haya en esa serie. Hay un problema, al tener más de un argumento no me entiende

In [ ]:
df["nosemeocurre"] = df.region.apply(empiezapora("NOEMPIEZAPORA", "¿CÓMO C*** LE DIGO A PANDAS QUE AQUÍ VA CADA REGISTRO?"))

AttributeError: 'NOEMPIEZAPORA' is not a valid function for 'Series' object

In [ ]:
# no puedo, tengo que hacerlo con lambda como hemos hecho arriba
df['nosecomollamarla'] = df.region.apply(lambda fila: empiezapora('noempiezapora', fila))

In [ ]:
df.sample(15)

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region,nosecomollamarla
11451,2015-04-12,1.94,4030.76,527.44,1873.44,722.33,907.55,776.67,130.88,0.00,organic,2015,SouthCarolina,noempiezapora
5915,2017-05-07,1.71,174746.25,1772.26,87260.23,209.65,85504.11,84212.76,1291.35,0.00,conventional,2017,BuffaloRochester,noempiezapora
12449,2016-01-24,1.42,11874.46,411.54,7551.79,0.00,3911.13,186.67,3724.46,0.00,organic,2016,CincinnatiDayton,noempiezapora
8975,2018-02-18,1.23,447962.28,152250.41,119244.74,18614.87,157852.26,147616.58,7409.57,2826.11,conventional,2018,SanDiego,noempiezapora
5006,2016-09-18,1.50,813575.88,173635.07,549722.44,9254.46,80963.91,75829.93,3098.42,2035.56,conventional,2016,SanFrancisco,noempiezapora
9198,2015-08-09,2.01,5579.38,2291.03,2855.35,0.00,433.00,49.96,383.04,0.00,organic,2015,Atlanta,noempiezapora
4804,2016-08-07,1.10,266174.10,98312.66,93057.33,8281.61,66522.50,60015.34,4302.16,2205.00,conventional,2016,RichmondNorfolk,noempiezapora
2983,2016-08-14,0.93,88787.27,43525.98,1959.35,6569.03,36732.91,36020.50,671.26,41.15,conventional,2016,Boise,noempiezapora
2374,2015-05-03,0.78,6558729.33,3520801.33,2265493.71,58510.13,713924.16,546260.44,166650.78,1012.94,conventional,2015,SouthCentral,noempiezapora
8752,2018-01-14,1.28,2409159.60,1104367.71,403918.08,101443.02,799430.79,739977.40,16783.17,42670.22,conventional,2018,LosAngeles,noempiezapora
4344,2016-06-12,1.34,4599028.54,201927.90,2903948.28,135414.25,1357738.11,1246079.71,80946.35,30712.05,conventional,2016,Northeast,Northeast
16410,2017-07-02,2.17,8059.10,811.06,4168.04,0.00,3080.00,3080.00,0.00,0.00,organic,2017,Orlando,noempiezapora
6038,2017-01-08,1.28,219338.92,56739.54,80201.70,10231.86,72165.82,63539.28,8626.54,0.00,conventional,2017,Charlotte,noempiezapora
15479,2017-01-22,0.77,19452.17,645.63,4104.58,0.00,14701.96,1331.38,13370.58,0.00,organic,2017,Detroit,noempiezapora
9956,2015-01-11,1.69,58061.65,4362.25,44552.46,0.00,9146.94,7266.75,1880.19,0.00,organic,2015,GreatLakes,noempiezapora

Cuando hago un apply sobre una columna, aunque use un lambda, no pongo axis porque en el caso de abajo, lo que estoy haciendo es modificar una columna, utilizo lambda para decirle al apply que el primer argumento es un string que viene de fuera y el segundo argumento es el propio registro del dataframe.

[Artículo Medium](https://towardsdatascience.com/apply-and-lambda-usage-in-pandas-b13a1ea037f7)     
[Otro Artículo](https://www.geeksforgeeks.org/applying-lambda-functions-to-pandas-dataframe/)      
[La DOCU es tu amiga](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html)

# Df **.loc** e **.iloc**
---

### Seleccionar filas y columnas en Pandas mediante posición con iloc

El método iloc se utiliza en los DataFrames para seleccionar los elementos en base a su ubicación. Su sintaxis es **data.iloc[`filas`, `columnas`]**, donde `filas` y `columnas` son la posición de las filas y columnas que se desean seleccionar en el orden que aparecen en el objeto.
En un DataFrame cada una de las filas tiene un número que va desde 0 hasta el total de filas menos uno. Siendo iloc el método que permite seleccionar los datos en base a estos números. Lo mismo que aplica a las columnas.

En iloc hay dos argumentos filas y columnas. En caso de que se omita el segundo, se seleccionarán todas las columnas de la fila. Así para seleccionar diferentes filas se puede utilizar.

In [ ]:
df.head(2)

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region,nosecomollamarla
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,noempiezapora
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,noempiezapora

In [ ]:
df[['average_price', 'total_volume']]

       average_price  total_volume
0               1.33      64236.62
1               1.35      54876.98
2               0.93     118220.22
3               1.08      78992.15
4               1.28      51039.60
...              ...           ...
18244           1.63      17074.83
18245           1.71      13888.04
18246           1.87      13766.76
18247           1.93      16205.22
18248           1.62      17489.58

[18249 rows x 2 columns]

In [ ]:
df[(df['year'] == 2015) & ((df['region'] == 'Albany') | (df['region'] == 'SanDiego'))][['average_price', 'region', 'year']]

       average_price    region  year
0               1.33    Albany  2015
1               1.35    Albany  2015
2               0.93    Albany  2015
3               1.08    Albany  2015
4               1.28    Albany  2015
...              ...       ...   ...
11305           1.11  SanDiego  2015
11306           1.26  SanDiego  2015
11307           1.29  SanDiego  2015
11308           1.05  SanDiego  2015
11309           1.23  SanDiego  2015

[208 rows x 3 columns]

In [ ]:
print(df.columns)

Index(['fecha', 'average_price', 'total_volume', '4046', '4225', '4770',
       'total_bags', 'small_bags', 'large_bags', 'xlarge_bags', 'type', 'year',
       'region', 'nosecomollamarla'],
      dtype='object')

In [ ]:
#seleccionamos un registro completo
df.iloc[0]

fecha               2015-12-27 00:00:00
average_price                      1.33
total_volume                   64236.62
4046                            1036.74
4225                           54454.85
4770                              48.16
total_bags                      8696.87
small_bags                      8603.62
large_bags                        93.25
xlarge_bags                         0.0
type                       conventional
year                               2015
region                           Albany
nosecomollamarla          noempiezapora
Name: 0, dtype: object

In [ ]:
# selección de ese registro completo en formato DataFrame
df.iloc[[0]]

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region,nosecomollamarla
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,noempiezapora

In [ ]:
#un rango de registros con slicing como en las cadenas
df.iloc[0:5:2]

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region,nosecomollamarla
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,noempiezapora
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,noempiezapora
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany,noempiezapora

Pequeño apunte: yo puedo recorrer `df.columns`, por ejemplo con `enumerate()` y así obtener tuplas con el índice y el nombre de cada columna...
```python
for i, col in enumerate(df.columns):
  print(i, col)
```
Pero hay una manera para saber el índice de una columna concreta:
**`.get_loc()`**
```python
df.columns.get_loc('columna')
```

In [ ]:
df.columns.get_loc('average_price')

1

In [ ]:
# Registros de la columna cuyo índice es el 1
df.iloc[0::2, [1]] #que registro nos hemos traido?

       average_price
0               1.33
2               0.93
4               1.28
6               0.99
8               1.02
...              ...
18240           1.54
18242           1.56
18244           1.63
18246           1.87
18248           1.62

[9125 rows x 1 columns]

In [ ]:
df.iloc[0::2, [df.columns.get_loc('average_price')]]

       average_price
0               1.33
2               0.93
4               1.28
6               0.99
8               1.02
...              ...
18240           1.54
18242           1.56
18244           1.63
18246           1.87
18248           1.62

[9125 rows x 1 columns]

In [ ]:
df.iloc[0:5, 1] # El segundo argumento, en este caso el número 1, es la columna.
                # el uso de corchetes extra en el interior es lo que hace que veamos la salida en uno u otro formato

0    1.33
1    1.35
2    0.93
3    1.08
4    1.28
Name: average_price, dtype: float64

In [ ]:
df.iloc[0:5, [1,3]] #Traigo la columna indice 1 y la 3
                    # en el momento que estamos seleccionando información con varias columnas ya nos muestra DF

   average_price     4046
0           1.33  1036.74
1           1.35   674.28
2           0.93   794.70
3           1.08  1132.00
4           1.28   941.48

### COLUMNAS POR RANGO

In [ ]:
df.head()

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region,nosecomollamarla
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,noempiezapora
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,noempiezapora
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,noempiezapora
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany,noempiezapora
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany,noempiezapora

In [ ]:
df.iloc[14:19, 2:5]

    total_volume     4046      4225
14      69759.01  1028.03  59313.12
15      76111.27   985.73  65696.86
16      99172.96   879.45  90062.62
17     105693.84   689.01  94362.67
18      79992.09   733.16  67933.79

### Seleccionar filas y columnas en Pandas en base a etiquetas con loc
El método loc se puede usar de dos formas diferentes:
- Seleccionar filas o columnas en base a una **etiqueta**.
- Seleccionar filas o columnas en base a una **condición**.

#### En base a etiqueta:

In [ ]:
# tal como está el DF en este momento los índices son posicionales
# primero vamos a setear las fechas como si fueran los índices

In [ ]:
# Loc busca DENTRO del INDEX algo concreto
df_index_date = df.set_index("fecha") #Creo un data nuevo para probar en el que el index es la fecha
df_index_date.head(3)

,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region,nosecomollamarla
fecha,,,,,,,,,,,,,
2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,noempiezapora
2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,noempiezapora
2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,noempiezapora

In [ ]:
df_index_date.loc["2015-12-06"].head() # Busco una fecha dentro del index con LOC

,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region,nosecomollamarla
fecha,,,,,,,,,,,,,
2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.00,conventional,2015,Albany,noempiezapora
2015-12-06,1.07,357636.82,283024.01,23740.85,181.92,50690.04,37032.67,13654.66,2.71,conventional,2015,Atlanta,noempiezapora
2015-12-06,1.04,649141.25,51129.29,453586.50,25760.49,118664.97,117112.77,1552.20,0.00,conventional,2015,BaltimoreWashington,noempiezapora
2015-12-06,0.71,95295.34,35590.98,12526.50,4086.26,43091.60,42734.53,0.00,357.07,conventional,2015,Boise,noempiezapora
2015-12-06,1.02,488679.31,5126.32,407520.22,142.99,75889.78,75666.22,223.56,0.00,conventional,2015,Boston,noempiezapora

In [ ]:
df_index_date.loc["2015-12-06"].shape # así veo el tamaño que tiene esta selección
                                      # ahora tiene 12 columnas y antes 13...?
                                      # la columna que he puesto como índices no cuenta como columna

(107, 13)

In [ ]:
df_index_date.loc["2015-12-06", ['total_bags', 'small_bags', 'large_bags', 'xlarge_bags']].head()

            total_bags  small_bags  large_bags  xlarge_bags
fecha
2015-12-06     5811.16     5677.40      133.76         0.00
2015-12-06    50690.04    37032.67    13654.66         2.71
2015-12-06   118664.97   117112.77     1552.20         0.00
2015-12-06    43091.60    42734.53        0.00       357.07
2015-12-06    75889.78    75666.22      223.56         0.00

In [ ]:
# se puede hacer de este otro modo
df_index_date.loc["2015-12-06":'2016-05-15'][['total_bags', 'small_bags', 'large_bags', 'xlarge_bags']].head()

            total_bags  small_bags  large_bags  xlarge_bags
fecha
2015-12-27     8696.87     8603.62       93.25          0.0
2015-12-20     9505.56     9408.07       97.49          0.0
2015-12-13     8145.35     8042.21      103.14          0.0
2015-12-06     5811.16     5677.40      133.76          0.0
2015-12-27    66354.31    48605.95    17748.36          0.0

In [ ]:
df_index_date[['total_bags', 'small_bags', 'large_bags', 'xlarge_bags']][['2015-12-06']] # así no puedo hacerlo
                                                                                         # necesito el índice de posición

KeyError: "None of [Index(['2015-12-06'], dtype='object')] are in the [columns]"

**`.loc[]`**
Permite filtrar el DataFrame con condiciones, pero se puede hacer lo mismo sin necesidad de loc.

In [ ]:
filtrado = df.loc[(df["year"] > 2014) & (df["region"]=="Albany")] #Loc funciona pero realmnte NO LO NECESITO

In [ ]:
filtrado.head(3)

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region,nosecomollamarla
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,noempiezapora
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,noempiezapora
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,noempiezapora

In [ ]:
filtrado2 = df[(df['year'] > 2014) & (df['region'] == 'Albany')] #Lo mismo pero sin loc

In [ ]:
filtrado2

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region,nosecomollamarla
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany,noempiezapora
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany,noempiezapora
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany,noempiezapora
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany,noempiezapora
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany,noempiezapora
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17608,2018-02-04,1.52,4124.96,118.38,420.36,0.00,3586.22,3586.22,0.00,0.0,organic,2018,Albany,noempiezapora
17609,2018-01-28,1.32,6987.56,433.66,374.96,0.00,6178.94,6178.94,0.00,0.0,organic,2018,Albany,noempiezapora
17610,2018-01-21,1.54,3346.54,14.67,253.01,0.00,3078.86,3078.86,0.00,0.0,organic,2018,Albany,noempiezapora
17611,2018-01-14,1.47,4140.95,7.30,301.87,0.00,3831.78,3831.78,0.00,0.0,organic,2018,Albany,noempiezapora
17612,2018-01-07,1.54,4816.90,43.51,412.17,0.00,4361.22,4357.89,3.33,0.0,organic,2018,Albany,noempiezapora

In [ ]:
for a in filtrado.columns:
    lista1 = filtrado[a].to_list() #creamos una lista con los valores de la columna
    lista2 = filtrado2[a].to_list() #creamos una lista con los valores de la columna
    #comparamos si los valores de las columnas son iguales
    if lista1 == lista2: print(f'columna {a} es igual en los df')

### Sintaxis del loc con varias condiciones
```python
df.loc[(df["columna"] condición) & (df["columna"] condición)]
````

Misma operación, pero dame solo columnas concretas

In [ ]:
# Esta selección de columnas la vimos al principio, pasarle una lista para que coja solo las columnas que quiero
filtrado_ = df.loc[(df["year"] > 2014) & (df["region"]=="Albany"), ["type", "year", "region"]]
filtrado_.head()

           type  year  region
0  conventional  2015  Albany
1  conventional  2015  Albany
2  conventional  2015  Albany
3  conventional  2015  Albany
4  conventional  2015  Albany

In [ ]:
df[(df["year"] > 2014) & (df["region"]=="Albany")][["type", "year", "region"]]

               type  year  region
0      conventional  2015  Albany
1      conventional  2015  Albany
2      conventional  2015  Albany
3      conventional  2015  Albany
4      conventional  2015  Albany
...             ...   ...     ...
17608       organic  2018  Albany
17609       organic  2018  Albany
17610       organic  2018  Albany
17611       organic  2018  Albany
17612       organic  2018  Albany

[338 rows x 3 columns]

OPERADOR NOT

In [ ]:
filtrado_.year.unique()

array([2015, 2016, 2017, 2018], dtype=int16)

In [ ]:
# ~ esto es una virgulilla
# sirve para negar una condición

In [ ]:
filtrado_[~(filtrado_['year'] == 2015)] # muestra aquellos resultados que en el df filtrado_ no cumplan esa condición

               type  year  region
2808   conventional  2016  Albany
2809   conventional  2016  Albany
2810   conventional  2016  Albany
2811   conventional  2016  Albany
2812   conventional  2016  Albany
...             ...   ...     ...
17608       organic  2018  Albany
17609       organic  2018  Albany
17610       organic  2018  Albany
17611       organic  2018  Albany
17612       organic  2018  Albany

[234 rows x 3 columns]

In [ ]:
df[(df["year"] == 2016) & ((df["region"] == "Albany") | (df['region'] == 'SanDiego'))]

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region,nosecomollamarla
2808,2016-12-25,1.52,73341.73,3202.39,58280.33,426.92,11432.09,11017.32,411.83,2.94,conventional,2016,Albany,noempiezapora
2809,2016-12-18,1.53,68938.53,3345.36,55949.79,138.72,9504.66,8876.65,587.73,40.28,conventional,2016,Albany,noempiezapora
2810,2016-12-11,1.49,71777.85,2323.39,56545.79,86.65,12822.02,12176.75,645.27,0.00,conventional,2016,Albany,noempiezapora
2811,2016-12-04,1.48,113031.96,6530.78,99746.05,50.84,6704.29,6476.12,228.17,0.00,conventional,2016,Albany,noempiezapora
2812,2016-11-27,1.52,58171.89,2793.99,47106.18,18.14,8253.58,7973.98,279.60,0.00,conventional,2016,Albany,noempiezapora
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14112,2016-01-31,1.40,11694.11,1123.30,7131.28,12.78,3426.75,444.06,2982.69,0.00,organic,2016,SanDiego,noempiezapora
14113,2016-01-24,1.31,15316.04,1368.36,8300.29,0.00,5647.39,756.65,4890.74,0.00,organic,2016,SanDiego,noempiezapora
14114,2016-01-17,1.46,12118.57,1919.40,5839.47,0.00,4359.70,710.23,3649.47,0.00,organic,2016,SanDiego,noempiezapora
14115,2016-01-10,1.32,12435.43,1414.85,5266.26,0.00,5754.32,515.58,5238.74,0.00,organic,2016,SanDiego,noempiezapora
14116,2016-01-03,1.41,10975.51,1991.55,5916.03,0.00,3067.93,614.85,2453.08,0.00,organic,2016,SanDiego,noempiezapora

In [ ]:
df.columns

## Ordenamos un dataframe

In [ ]:
df.head(2)

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany

In [ ]:
#df.drop(columns = 'nosecomollamarla', inplace = True)

In [ ]:
df.sort_values(by="year",ascending=False).head() #Ascending FALSE de mayor a menor

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region
9124,2018-01-14,0.90,950954.60,463945.73,188126.02,11227.47,287655.38,125408.69,162040.02,206.67,conventional,2018,WestTexNewMexico
8883,2018-01-21,0.78,1315329.83,613600.56,246703.53,13332.26,441693.48,210780.39,226079.75,4833.34,conventional,2018,PhoenixTucson
8905,2018-02-04,0.91,3316494.76,1609104.94,827998.81,9830.10,869560.91,678696.23,190573.14,291.54,conventional,2018,Plains
8906,2018-01-28,0.99,2533937.56,1387712.40,515698.93,6371.30,624154.93,474701.92,149437.52,15.49,conventional,2018,Plains
8907,2018-01-21,1.18,2208596.12,1051836.46,479599.90,7659.28,669500.48,562989.08,106461.22,50.18,conventional,2018,Plains

In [ ]:
df.sort_values(by="year",ascending=False)[["type"]] #Ascending FALSE de mayor a menor

               type
9124   conventional
8883   conventional
8905   conventional
8906   conventional
8907   conventional
...             ...
10278       organic
10279       organic
10280       organic
10281       organic
0      conventional

[18249 rows x 1 columns]

In [ ]:
guardar_ordenado = df.sort_values(by="large_bags") #Lo puedo guardar en una variable

In [ ]:
guardar_ordenado.head()

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region
12385,2016-04-17,1.55,25405.66,97.85,24629.54,0.00,678.27,678.27,0.0,0.0,organic,2016,Chicago
10610,2015-06-14,2.00,22931.78,5012.28,14260.60,923.15,2735.75,2735.75,0.0,0.0,organic,2015,NewYork
1762,2015-02-08,0.64,1151157.44,881998.68,184023.21,5517.00,79618.55,79618.55,0.0,0.0,conventional,2015,PhoenixTucson
1763,2015-02-01,0.56,1544750.92,1194635.06,261342.47,6335.66,82437.73,82437.73,0.0,0.0,conventional,2015,PhoenixTucson
1765,2015-01-18,0.67,1088608.66,811662.62,200514.36,5643.07,70788.61,70788.61,0.0,0.0,conventional,2015,PhoenixTucson

In [ ]:
df.sort_values(by="large_bags", ascending = False)

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region
9097,2018-02-04,0.87,62505646.52,21620180.90,20445501.03,1066830.22,19373134.37,13384586.80,5719096.61,269450.96,conventional,2018,TotalUS
8353,2017-05-07,1.09,47293921.60,17076650.82,13549102.59,863471.88,15804696.31,11228049.63,4324231.19,252415.49,conventional,2017,TotalUS
9094,2018-02-25,1.06,40021528.76,13829857.87,10415463.59,724330.16,15051877.14,10666942.78,4081397.72,303536.64,conventional,2018,TotalUS
9096,2018-02-11,0.97,43167806.09,15870677.70,11541844.87,652856.58,15102426.94,10844852.22,4023485.04,234089.68,conventional,2018,TotalUS
9091,2018-03-18,1.05,41386314.12,13707389.51,11061051.69,645380.85,15972492.07,11712807.19,3988101.74,271583.14,conventional,2018,TotalUS
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10054,2015-02-22,2.38,4834.37,670.44,3747.31,2.64,413.98,413.98,0.00,0.00,organic,2015,HartfordSpringfield
10053,2015-03-01,2.17,3050.04,59.15,2158.92,2.63,829.34,829.34,0.00,0.00,organic,2015,HartfordSpringfield
10052,2015-03-08,2.18,3286.02,152.85,2524.64,0.00,608.53,608.53,0.00,0.00,organic,2015,HartfordSpringfield
13017,2016-02-21,1.76,2679.98,1793.68,76.87,6.10,803.33,803.33,0.00,0.00,organic,2016,Jacksonville
10045,2015-04-26,2.24,2843.96,52.97,2160.59,5.16,625.24,625.24,0.00,0.00,organic,2015,HartfordSpringfield

In [ ]:
df.sort_values(by=["fecha", "region"]).head() #ORDENAR POR VARIAS COLUMNAS

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region
51,2015-01-04,1.22,40873.28,2819.50,28287.42,49.90,9716.46,9186.93,529.53,0.0,conventional,2015,Albany
9177,2015-01-04,1.79,1373.95,57.42,153.88,0.00,1162.65,1162.65,0.00,0.0,organic,2015,Albany
103,2015-01-04,1.00,435021.49,364302.39,23821.16,82.15,46815.79,16707.15,30108.64,0.0,conventional,2015,Atlanta
9229,2015-01-04,1.76,3846.69,1500.15,938.35,0.00,1408.19,1071.35,336.84,0.0,organic,2015,Atlanta
155,2015-01-04,1.08,788025.06,53987.31,552906.04,39995.03,141136.68,137146.07,3990.61,0.0,conventional,2015,BaltimoreWashington

In [ ]:
df.sort_values(by=["region", "fecha"]).head()

,fecha,average_price,total_volume,4046,4225,4770,total_bags,small_bags,large_bags,xlarge_bags,type,year,region
51,2015-01-04,1.22,40873.28,2819.50,28287.42,49.90,9716.46,9186.93,529.53,0.0,conventional,2015,Albany
9177,2015-01-04,1.79,1373.95,57.42,153.88,0.00,1162.65,1162.65,0.00,0.0,organic,2015,Albany
50,2015-01-11,1.24,41195.08,1002.85,31640.34,127.12,8424.77,8036.04,388.73,0.0,conventional,2015,Albany
9176,2015-01-11,1.77,1182.56,39.00,305.12,0.00,838.44,838.44,0.00,0.0,organic,2015,Albany
49,2015-01-18,1.17,44511.28,914.14,31540.32,135.77,11921.05,11651.09,269.96,0.0,conventional,2015,Albany

### Buscamos valores nulos

In [ ]:
# seaborn es una librería de visualización
import seaborn as sns
df_titanic = sns.load_dataset("titanic") #tips
df_titanic.shape

(891, 15)

#### ¿Es nulo?

In [ ]:
df_titanic.isna().sum() #.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

#### ¿Es NO nulo?

In [ ]:
df_titanic.notna().sum() #.notnull().sum()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [ ]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

#### Sacar una suma de los valores nulos de cada columna

In [ ]:
df_titanic.isna().sum()

In [ ]:
#Si somos muy cucos:
(df_titanic.isna().sum()/(df_titanic.shape[0])*100).round(2)

survived        0.00
pclass          0.00
sex             0.00
age            19.87
sibsp           0.00
parch           0.00
fare            0.00
embarked        0.22
class           0.00
who             0.00
adult_male      0.00
deck           77.22
embark_town     0.22
alive           0.00
alone           0.00
dtype: float64

### Borramos los valores nulos
Hay varias formas de hacerlo, tenemos en cuenta el parámetro "how" y, desde luego, [nos leemos la documentación](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html).

In [ ]:
df_titanic=sns.load_dataset("titanic")
df_titanic.shape

In [ ]:
#buscamos filas donde todos los registros sean NaN
df_titanic[df_titanic.isna().all(axis=1)]

Empty DataFrame
Columns: [survived, pclass, sex, age, sibsp, parch, fare, embarked, class, who, adult_male, deck, embark_town, alive, alone]
Index: []

In [ ]:
# estoy viendo que todas las filas por lo menos en alguna columna tiene algún valor

In [ ]:
df_titanic.index.max()

890

In [ ]:
df_titanic.dropna(how="all", inplace=True)#Con "all" borramos donde TODOS los registros sean NaN
df_titanic.shape

(891, 15)

In [ ]:
#añadimos a mano una fila con todos los registros NaN
df_titanic.loc[891] = [np.nan]*15

In [ ]:
df_titanic.tail(3)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
889,1.0,1.0,male,26.0,0.0,0.0,30.00,C,First,man,1.0,C,Cherbourg,yes,1.0
890,0.0,3.0,male,32.0,0.0,0.0,7.75,Q,Third,man,1.0,NaN,Queenstown,no,1.0
891,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_titanic.shape

(891, 15)

In [ ]:
df_titanic.dropna(how='all', inplace = True)

In [ ]:
df_titanic.tail(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
889,1.0,1.0,male,26.0,0.0,0.0,30.00,C,First,man,1.0,C,Cherbourg,yes,1.0
890,0.0,3.0,male,32.0,0.0,0.0,7.75,Q,Third,man,1.0,NaN,Queenstown,no,1.0

In [ ]:
df_titanic.dropna(inplace=True) #Borramos las filas con algún NaN

In [ ]:
df_titanic.shape

(182, 15)

In [ ]:
df_titanic = sns.load_dataset('titanic')

In [ ]:
df_titanic.dropna(inplace = True, axis=1)

In [ ]:
df_titanic.sample(15)

,survived,pclass,sex,sibsp,parch,fare,class,who,adult_male,alive,alone
346,1,2,female,0,0,13.0000,Second,woman,False,yes,True
232,0,2,male,0,0,13.5000,Second,man,True,no,True
513,1,1,female,1,0,59.4000,First,woman,False,yes,False
497,0,3,male,0,0,15.1000,Third,man,True,no,True
688,0,3,male,0,0,7.7958,Third,man,True,no,True
233,1,3,female,4,2,31.3875,Third,child,False,yes,False
554,1,3,female,0,0,7.7750,Third,woman,False,yes,True
216,1,3,female,0,0,7.9250,Third,woman,False,yes,True
445,1,1,male,0,2,81.8583,First,child,False,yes,False
576,1,2,female,0,0,13.0000,Second,woman,False,yes,True
355,0,3,male,0,0,9.5000,Third,man,True,no,True
458,1,2,female,0,0,10.5000,Second,woman,False,yes,True
602,0,1,male,0,0,42.4000,First,man,True,no,True
342,0,2,male,0,0,13.0000,Second,man,True,no,True
255,1,3,female,0,2,15.2458,Third,woman,False,yes,False

In [ ]:
# NUNCA BORRAMOS LOS NAN A LO LOCO, OS LO SUPLICO
# Si no pongo nada, axis = 0 entonces borra todas las filas que contengan un NaN da igual en qué columna
# SI PONGO 1 borramos las columnas

In [ ]:
# si hago drop axis=1 lo que borramos son las columnas, ESTO TAMPOCO LO HACEMOS POR FAVOR
df_titanic.dropna(how="all", axis=1)

In [ ]:
# BORRAMOS LOS REGISTROS DONDE TODO SEA NAN (poner axis=0 es lo mismo que nada porque viene por defecto)
# si hago drop axis=1 lo que borramos son las columnas, ESTO TAMPOCO LO HACEMOS POR FAVOR
df_titanic.dropna(how="all", axis=0)

In [ ]:
df.isna().sum()

In [ ]:
df_titanic.dropna(axis=1, inplace= True, thresh = 688) #el valor de thresh está incluido

In [ ]:
df_titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

RECORDAD QUE INPLACE TRUE ES PARA QUE EL MÉTODO ACCIONE SOBRE EL DF, SI NO, TENGO QUE GUARDARLO EN UNA VARIABLE NUEVA

🧨🧨🧨🧨

Con "any" (**parámetro por default**  👀 con no poner nada) se borran todos los registros en los que en ***alguna columna*** haya un NaN

🧨🧨🧨🧨

### Cómo rellenar los datos que faltan

¿Qué os parece un poquito de  📚[DOCU](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html)?

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
df_titanic = sns.load_dataset('titanic')
df_titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df_titanic.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df_titanic.age.mean().round(2)

29.7

In [ ]:
#FILLNA es el método que me va a permitir rellenar los NAN con lo que yo le ponga
df_titanic.age.fillna(df_titanic.age.mean().round(0), inplace=True)

In [ ]:
df_titanic.age.isna().sum()

0

In [ ]:
df_titanic.age.mean().round(2) #Si relleno con la media, como hemos demostrado la media de la columna no se mueve

29.76

In [ ]:
df_titanic.embarked.value_counts()

S    644
C    168
Q     77
Name: embarked, dtype: int64

In [ ]:
df_titanic.embarked.isna().sum()

2

In [ ]:
df_titanic.embarked.fillna("Polizón",inplace=True)

In [ ]:
df_titanic[df_titanic["embarked"] == "Polizón"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
61,1,1,female,38.0,0,0,80.0,Polizón,First,woman,False,B,NaN,yes,True
829,1,1,female,62.0,0,0,80.0,Polizón,First,woman,False,B,NaN,yes,True

In [ ]:
# por poner un poco de ejemplo sobre como rellenar NaN
# df_titanic[(df_titanic['deck'] == 'B') & (df_titanic['class'] == 'First')]

In [ ]:
df_titanic.embark_town.isnull().sum()

2

In [ ]:
df_titanic.embark_town.fillna("Desconocida", inplace = True)

In [ ]:
df_titanic.loc[df_titanic["embark_town"] == "Desconocida"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
61,1,1,female,38.0,0,0,80.0,Polizón,First,woman,False,B,Desconocida,yes,True
829,1,1,female,62.0,0,0,80.0,Polizón,First,woman,False,B,Desconocida,yes,True

##### CATEGÓRICAS EN DATAFRAME
🔎📚➡[DOCU](https://runebook.dev/es/docs/pandas/user_guide/categorical)

In [ ]:
import seaborn as sns

In [ ]:
df_titanic = sns.load_dataset("titanic")
df_titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
df_titanic.deck.value_counts()

C    59
B    47
D    33
E    32
A    15
F    13
G     4
Name: deck, dtype: int64

In [ ]:
(df_titanic.deck.isna().sum()/len(df_titanic.deck)*100).round(2)

77.22

In [ ]:
df_titanic.deck.values.categories #valores que toman las categorias

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='object')

In [ ]:
df_titanic.deck.fillna("Unknown", inplace=True) # ERROR LO DEJO A PROPÓSITO porque no puedo añadir una categoría que no está
# ValueError: Cannot setitem on a Categorical with a new category, set the categories first

TypeError: Cannot setitem on a Categorical with a new category (Unknown), set the categories first

In [ ]:
df_titanic.deck = df_titanic.deck.cat.add_categories("Desconocido")

In [ ]:
df_titanic.deck.values.categories

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'Desconocido'], dtype='object')

In [ ]:
df_titanic.deck.fillna("Desconocido", inplace=True) # Ahora ya puedo hacer fillna con Desconocido

In [ ]:
df_titanic.deck.value_counts()

Desconocido    688
C               59
B               47
D               33
E               32
A               15
F               13
G                4
Name: deck, dtype: int64

In [ ]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         891 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
df_titanic.sex = df_titanic.sex.astype('category')

In [ ]:
df_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    category
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         891 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(3), float64(2), int64(4), object(4)
memory usage: 74.7+ KB

In [ ]:
df_titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Desconocido,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Desconocido,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Desconocido,Southampton,no,True

In [ ]:
df_titanic.survived.sum()

342

In [ ]:
df_titanic.alone.sum()

537

## Borramos los duplicados

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
df_titanic = sns.load_dataset('titanic')

In [ ]:
df_titanic.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df_titanic.shape

(891, 15)

Tenemos que ver los datos que tenemos duplicados en los datos. Esto lo puedo mirar con .drop_duplicates()

Pero esto no me asegura cuántos duplicados únicos tengo:

In [ ]:
df_titanic.drop_duplicates()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

Salen 784 filas, una vez se han eliminado los registros duplicados. Pero puedo ver esa información para poder tomar la decisión más correcta. Dentro de la función está definido por defecto que de los duplicados deja el primer registro. Vamos a grabar el drop, en el momento de aplicar el inplace no me va a devolver nada:

In [ ]:
df_titanic.drop_duplicates(inplace = True, keep = 'first') # 'first ya es lo definido por defecto

In [ ]:
df_titanic.shape

(784, 15)

Vuelvo a cargar el dataset y vemos otra manera:

In [ ]:
df_titanic = sns.load_dataset('titanic')

In [ ]:
df_titanic[df_titanic.duplicated()] #aquí hay 107 filas, estoy viendo los duplicados únicos.

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
47,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
76,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
77,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
87,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
95,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,0,3,male,26.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True

In [ ]:
df_titanic.iloc[0:48]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
25,1,3,female,38.0,1,5,31.3875,S,Third,woman,False,NaN,Southampton,yes,False
26,0,3,male,NaN,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
28,1,3,female,NaN,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True
29,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
30,0,1,male,40.0,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
32,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
33,0,2,male,66.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
34,0,1,male,28.0,1,0,82.1708,C,First,man,True,NaN,Cherbourg,no,False
35,0,1,male,42.0,1,0,52.0000,S,First,man,True,NaN,Southampton,no,False
36,1,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,yes,True
37,0,3,male,21.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
39,1,3,female,14.0,1,0,11.2417,C,Third,child,False,NaN,Cherbourg,yes,False
40,0,3,female,40.0,1,0,9.4750,S,Third,woman,False,NaN,Southampton,no,False
41,0,2,female,27.0,1,0,21.0000,S,Second,woman,False,NaN,Southampton,no,False
42,0,3,male,NaN,0,0,7.8958,C,Third,man,True,NaN,Cherbourg,no,True
43,1,2,female,3.0,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
44,1,3,female,19.0,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True
45,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
46,0,3,male,NaN,1,0,15.5000,Q,Third,man,True,NaN,Queenstown,no,False
47,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True

Al hacerlo como un filtrado de datos puedo obserbar la muestra de toda la información que voy a eliminar.

Para que lo veamos gráficamente le estoy dando un false en keep y que me lo ordene por la lista de las columns, es como si le estuviese pasando que me lo ordene TODO por todas las columnas. keep = False -> No me saca el primer o el último registro, me saca TODOS, por defecto me va a mantener el primer registro y va a eliminar el resto de registros duplicados. Al declarar False el parámetro keep me está mostrando todos aquellos registros (filas completas) que contienen la misma información.

Al hacer esto veo los registros que son exactamente iguales juntos. De esta manera siempre me van a aparecer juntos.

In [ ]:
df_titanic[df_titanic.duplicated(keep=False)].sort_values(by=df_titanic.columns.tolist())

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
64,0,1,male,NaN,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
295,0,1,male,NaN,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
144,0,2,male,18.0,0,0,11.5000,S,Second,man,True,NaN,Southampton,no,True
757,0,2,male,18.0,0,0,11.5000,S,Second,man,True,NaN,Southampton,no,True
658,0,2,male,23.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
838,1,3,male,32.0,0,0,56.4958,S,Third,man,True,NaN,Southampton,yes,True
643,1,3,male,NaN,0,0,56.4958,S,Third,man,True,NaN,Southampton,yes,True
692,1,3,male,NaN,0,0,56.4958,S,Third,man,True,NaN,Southampton,yes,True
65,1,3,male,NaN,1,1,15.2458,C,Third,man,True,NaN,Cherbourg,yes,False
709,1,3,male,NaN,1,1,15.2458,C,Third,man,True,NaN,Cherbourg,yes,False

keep = 'first' -> entre el 64 y el 295 únicamente me mostraría el 64.

keep = 'last' -> entre el 64 y el 295 únicamente me mostraría el 295.

keep = False -> me mostrará ambas filas.

# Agregación de datos
## GroupBy (nos suena?? 🤔)
GroupBy de Pandas es una función potente y versátil en Python. Nos permite dividir sus datos en grupos separados para realizar cálculos para un mejor análisis.
Un DataFrame puede agruparse en sus filas (eje=0) o en sus columnas (eje=1). Una vez hecho esto, se aplica una función a cada grupo, produciendo un nuevo valor. Finalmente, los resultados de todas esas aplicaciones de funciones se combinan en un objeto resultado. La forma del objeto resultante dependerá normalmente de lo que se haga con los datos.

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html

Vamos a crear un df sencillito para entender bien como va la cosa

In [ ]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'], 'key2' : ['one', 'two', 'one', 'two', 'one'],'data1' : np.random.randn(5),'data2' : np.random.randn(5)})

In [ ]:
df.head()

  key1 key2     data1     data2
0    a  one  1.047792  0.783419
1    a  two -1.878459  1.130080
2    b  one  0.940551  2.932891
3    b  two  1.078565  0.212606
4    a  one  0.969516  0.190154

Supongamos que queremos calcular la media de la columna data1 utilizando las etiquetas de key1. Hay varias formas de hacerlo. Una es acceder a datos1 y llamar a groupby con la columna (una Serie) en key1.
Los datos (una Serie) han sido agregados según la clave de grupo, produciendo una nueva Serie que ahora está indexada por los valores únicos de la columna clave1. El índice resultante tiene el nombre 'clave1' porque la columna DataFrame `df['clave1']` lo hizo.

In [ ]:
group = df["data1"].groupby(df["key1"]).mean()

In [ ]:
group # ESTO ES UNA SERIE DE PANDAS

key1
a    0.046283
b    1.009558
Name: data1, dtype: float64

In [ ]:
type(group)

pandas.core.series.Series

In [ ]:
dataframe = pd.DataFrame(df["data1"].groupby(df["key1"]).mean())

In [ ]:
dataframe

         data1
key1
a     0.046283
b     1.009558

In [ ]:
df[["data1"]].groupby(df["key1"]).mean()

         data1
key1
a     0.046283
b     1.009558

In [ ]:
avocado = pd.read_csv('/content/drive/MyDrive/gamma/Data/00. Data/avocado.csv')
avocado.sample()

,Unnamed: 0,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
13675,26,2016-06-26,1.66,13866.31,6127.86,4823.04,0.0,2915.41,647.76,2267.65,0.0,organic,2016,PhoenixTucson

In [ ]:
avocado[["AveragePrice"]].groupby(avocado["type"]).mean()

              AveragePrice
type
conventional      1.158040
organic           1.653999

### Pero, ¿y si quiero agrupar por más columnas?

In [ ]:
df

  key1 key2     data1     data2
0    a  one  1.047792  0.783419
1    a  two -1.878459  1.130080
2    b  one  0.940551  2.932891
3    b  two  1.078565  0.212606
4    a  one  0.969516  0.190154

In [ ]:
df.groupby(["key1", "key2"]).mean()

              data1     data2
key1 key2
a    one   1.008654  0.486787
     two  -1.878459  1.130080
b    one   0.940551  2.932891
     two   1.078565  0.212606

Otra forma de groupby con sintaxis agg     
https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.aggregate.html

- mean
- sum
- count

In [ ]:
df.groupby("key1").agg({"data1": "sum"})

         data1
key1
a     0.138849
b     2.019116

In [ ]:
df.groupby(["key1"])[["data1"]].sum()

         data1
key1
a     0.138849
b     2.019116

In [ ]:
df.groupby("key2").agg({"data1": "sum", "data2":"mean"})

         data1     data2
key2
one   2.957859  1.302155
two  -0.799895  0.671343

In [ ]:
# así no puedo aplicar las operaciones distintas para cada columna
df.groupby("key1")[['data1', 'data2']].sum().mean()

data1    1.078982
data2    2.624575
dtype: float64

In [ ]:
avocado.sample()

In [ ]:
avocado.groupby("region").agg({"AveragePrice":"mean", "Total Bags": "sum"})

                     AveragePrice    Total Bags
region
Albany                   1.561036  2.680255e+06
Atlanta                  1.337959  2.856051e+07
BaltimoreWashington      1.534231  3.530615e+07
Boise                    1.348136  5.399412e+06
Boston                   1.530888  2.149548e+07
BuffaloRochester         1.516834  1.161075e+07
California               1.395325  2.466822e+08
Charlotte                1.606036  1.169794e+07
Chicago                  1.556775  1.686540e+07
CincinnatiDayton         1.209201  2.089792e+07
Columbus                 1.252781  1.001639e+07
DallasFtWorth            1.085592  4.646975e+07
Denver                   1.218580  5.895701e+07
Detroit                  1.276095  2.426007e+07
GrandRapids              1.505000  9.169094e+06
GreatLakes               1.338550  1.785756e+08
HarrisburgScranton       1.513284  1.352925e+07
HartfordSpringfield      1.818639  1.133301e+07
Houston                  1.047929  5.021506e+07
Indianapolis             1.313994  1.198081e+07
Jacksonville             1.510947  9.718127e+06
LasVegas                 1.380917  1.805299e+07
LosAngeles               1.216006  1.682645e+08
Louisville               1.286686  6.635289e+06
MiamiFtLauderdale        1.428491  2.351644e+07
Midsouth                 1.404763  1.565136e+08
Nashville                1.212101  1.296717e+07
NewOrleansMobile         1.304793  1.426894e+07
NewYork                  1.727574  6.799416e+07
Northeast                1.601923  1.969884e+08
NorthernNewEngland       1.477396  1.390503e+07
Orlando                  1.506213  1.686164e+07
Philadelphia             1.632130  2.387523e+07
PhoenixTucson            1.224438  3.890824e+07
Pittsburgh               1.364320  7.245462e+06
Plains                   1.436509  7.784720e+07
Portland                 1.317722  4.950436e+07
RaleighGreensboro        1.555118  1.567668e+07
RichmondNorfolk          1.291331  1.250823e+07
Roanoke                  1.247929  9.590988e+06
Sacramento               1.621568  8.982268e+06
SanDiego                 1.398166  2.334267e+07
SanFrancisco             1.804201  1.489092e+07
Seattle                  1.442574  5.069140e+07
SouthCarolina            1.403284  1.815317e+07
SouthCentral             1.101243  2.333924e+08
Southeast                1.398018  1.815276e+08
Spokane                  1.445592  6.254376e+06
StLouis                  1.430621  1.473603e+07
Syracuse                 1.520325  4.192427e+06
Tampa                    1.408846  1.949669e+07
TotalUS                  1.319024  1.638601e+09
West                     1.272219  3.670736e+08
WestTexNewMexico         1.261701  3.529652e+07

In [ ]:
meloguardo = avocado.groupby(["region", "type"]).agg({"AveragePrice":"mean", "Total Bags": "sum"})

In [ ]:
meloguardo.head(20)

                                  AveragePrice    Total Bags
region              type
Albany              conventional      1.348757  2.366259e+06
                    organic           1.773314  3.139954e+05
Atlanta             conventional      1.068817  2.759711e+07
                    organic           1.607101  9.634084e+05
BaltimoreWashington conventional      1.344201  3.305902e+07
                    organic           1.724260  2.247123e+06
Boise               conventional      1.076036  5.151787e+06
                    organic           1.620237  2.476254e+05
Boston              conventional      1.304379  1.932035e+07
                    organic           1.757396  2.175131e+06
BuffaloRochester    conventional      1.382308  1.074232e+07
                    organic           1.651361  8.684365e+05
California          conventional      1.105444  2.378415e+08
                    organic           1.685207  8.840647e+06
Charlotte           conventional      1.275089  1.120896e+07
                    organic           1.936982  4.889827e+05
Chicago             conventional      1.369349  1.629280e+07
                    organic           1.744201  5.726041e+05
CincinnatiDayton    conventional      1.015503  1.962984e+07
                    organic           1.402899  1.268081e+06

In [ ]:
meloguardo.index

MultiIndex([(             'Albany', 'conventional'),
            (             'Albany',      'organic'),
            (            'Atlanta', 'conventional'),
            (            'Atlanta',      'organic'),
            ('BaltimoreWashington', 'conventional'),
            ('BaltimoreWashington',      'organic'),
            (              'Boise', 'conventional'),
            (              'Boise',      'organic'),
            (             'Boston', 'conventional'),
            (             'Boston',      'organic'),
            ...
            (           'Syracuse', 'conventional'),
            (           'Syracuse',      'organic'),
            (              'Tampa', 'conventional'),
            (              'Tampa',      'organic'),
            (            'TotalUS', 'conventional'),
            (            'TotalUS',      'organic'),
            (               'West', 'conventional'),
            (               'West',      'organic'),
            (   'WestTexNewMexico', 'conventional'),
            (   'WestTexNewMexico',      'organic')],
           names=['region', 'type'], length=108)

In [ ]:
meloguardo.loc[[('Albany'),('Atlanta')]]

                      AveragePrice   Total Bags
region  type
Albany  conventional      1.348757   2366259.23
        organic           1.773314    313995.38
Atlanta conventional      1.068817  27597105.14
        organic           1.607101    963408.44

In [ ]:
df_titanic.groupby(["sex", "class"])[['age']].mean()

                     age
sex    class
female First   34.611765
       Second  28.722973
       Third   21.750000
male   First   41.281386
       Second  30.740707
       Third   26.507589

In [ ]:
df_titanic.groupby(["sex", "class"]).agg({"age":["mean", 'max', 'min']})

                     age
                    mean   max   min
sex    class
female First   34.611765  63.0  2.00
       Second  28.722973  57.0  2.00
       Third   21.750000  63.0  0.75
male   First   41.281386  80.0  0.92
       Second  30.740707  70.0  0.67
       Third   26.507589  74.0  0.42

## Uniendo de Dataframes
- https://realpython.com/pandas-merge-join-and-concat/
- https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html


## Concat
Unimos dataframes a lo largo del axis 0 uno debajo de otro. Alinea las columnas por etiqueta. Lo que viene siendo un union de SQL verdad?

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user',
                  sep='|',
                  index_col='user_id')

In [ ]:
df.head()

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213

Puedo cargar fácilmente datos desde una URL

---

Esto es posible cuando la URL nos lleva directamente al archivo.

En este caso aunque sea un archivo CSV no se usan comas como separador, así que por eso se le indica qué es lo que debe de usar como separador.

`sep = |`

In [ ]:
df.shape

(943, 4)

In [ ]:
uno=df.sample(frac=0.3)
dos=df.sample(frac=0.4)

In [ ]:
uno.head()

         age gender     occupation zip_code
user_id
521       19      M        student    02146
255       23      M  entertainment    07029
871       31      M      executive    44648
273       50      F          other    10016
467       29      M       engineer    91201

In [ ]:
dos.head()

         age gender  occupation zip_code
user_id
825       44      M    engineer    05452
108       44      M    educator    63130
919       25      M       other    14216
325       48      M  technician    02139
306       45      M       other    73132

In [ ]:
uno.shape, dos.shape

((283, 4), (377, 4))

In [ ]:
pd.concat([uno, dos]).head()  # esto recibe una lista de dataframes

         age gender     occupation zip_code
user_id
521       19      M        student    02146
255       23      M  entertainment    07029
871       31      M      executive    44648
273       50      F          other    10016
467       29      M       engineer    91201

In [ ]:
concatenado=pd.concat([uno, dos])

concatenado.shape

(660, 4)

In [ ]:
# Podemos concatenar uno al lado del otro pero tienen que tener el mismo número de filas

In [ ]:
concat_h=pd.concat([uno, dos], axis=1)

In [ ]:
# se quedan muchos nan al concatenar horizontalmente dos df (es como un full outer join)
concat_h

,age,gender,occupation,zip_code,age,gender,occupation,zip_code
user_id,,,,,,,,
521,19.0,M,student,02146,NaN,NaN,NaN,NaN
255,23.0,M,entertainment,07029,23.0,M,entertainment,07029
871,31.0,M,executive,44648,NaN,NaN,NaN,NaN
273,50.0,F,other,10016,50.0,F,other,10016
467,29.0,M,engineer,91201,29.0,M,engineer,91201
...,...,...,...,...,...,...,...,...
608,NaN,NaN,NaN,NaN,22.0,M,other,10003
791,NaN,NaN,NaN,NaN,31.0,M,educator,20064
450,NaN,NaN,NaN,NaN,35.0,F,educator,11758
285,NaN,NaN,NaN,NaN,25.0,M,programmer,53713
340,NaN,NaN,NaN,NaN,46.0,M,engineer,80123

### Merge

[Merge()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html) es más útil cuando se desea combinar filas que comparten datos.

In [ ]:
df1=pd.DataFrame({'lkey': ['k0', 'k1', 'k2'],
                   'B': [1, 2, 3]})

df2=pd.DataFrame({'rkey': ['k0', 'k1', 'k2'],
                   'B': [4, 6, 7]})

In [ ]:
df3=pd.DataFrame({'rkey': ['k0', 'k1', 'k2'],
                   'Otracol': [4, 6, 7]})

In [ ]:
df1.head()

  lkey  B
0   k0  1
1   k1  2
2   k2  3

In [ ]:
df2.head()

  rkey  B
0   k0  4
1   k1  6
2   k2  7

In [ ]:
mergeado=df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=['_izq', '_dcha'])

mergeado

  lkey  B_izq rkey  B_dcha
0   k0      1   k0       4
1   k1      2   k1       6
2   k2      3   k2       7

In [ ]:
df3.head()

  rkey  Otracol
0   k0        4
1   k1        6
2   k2        7

In [ ]:
mer_merge=mergeado.merge(df3, left_on='lkey', right_on='rkey') #, suffixes = ['_yaesta', '_nuevo'] esto es otro argumento que le puedo pasar para identificar mejor las columnas

In [ ]:
mer_merge.head()

  lkey  B_izq rkey_x  B_dcha rkey_y  Otracol
0   k0      1     k0       4     k0        4
1   k1      2     k1       6     k1        6
2   k2      3     k2       7     k2        7

In [ ]:
# Una vez hemos mergeado, nos interesa eliminar la columna repetida

In [ ]:
mer_merge.drop(columns=['rkey_x', 'rkey_y'])

  lkey  B_izq  B_dcha  Otracol
0   k0      1       4        4
1   k1      2       6        6
2   k2      3       7        7

# Cuando no me coinciden los datos

In [ ]:
df1=pd.DataFrame({'lkey': ['k0', 'k1', 'k2'],
                   'B': [1, 2, 3]})

df2=pd.DataFrame({'rkey': ['k0', 'k1', 'k3'],
                   'B': [4, 6, 7]})

In [ ]:
df1

  lkey  B
0   k0  1
1   k1  2
2   k2  3

In [ ]:
df2

  rkey  B
0   k0  4
1   k1  6
2   k3  7

In [ ]:
# how =
# 'outer' --> full join
# 'left' --> left join
# 'right' --> right join
# sin argumento --> inner
df1.merge(df2, left_on='lkey', right_on='rkey')

  lkey  B_x rkey  B_y
0   k0    1   k0    4
1   k1    2   k1    6

In [ ]:
uno_2=pd.DataFrame({'nombre_uno': ['ras', 'sonia', 'ana', 'dobby', 'k4'],
                  'dirección': ['calle fantasía', 'a1', 'a2', 'a3', 'a4']})

otro_2=pd.DataFrame({'nombre_dos': ['ras', 'ana', 'sonia'],
                  'teléfono': ['7245689247', 'b1', 'b2']})

In [ ]:
 # Si no pongo how es un INNER y borra donde no haya match

In [ ]:
uno_2.merge(otro_2, left_on='nombre_uno', right_on='nombre_dos')

  nombre_uno       dirección nombre_dos    teléfono
0        ras  calle fantasía        ras  7245689247
1      sonia              a1      sonia          b2
2        ana              a2        ana          b1

In [ ]:
uno_2.merge(otro_2, left_on='nombre_uno', right_on='nombre_dos', how = 'left')

  nombre_uno       dirección nombre_dos    teléfono
0        ras  calle fantasía        ras  7245689247
1      sonia              a1      sonia          b2
2        ana              a2        ana          b1
3      dobby              a3        NaN         NaN
4         k4              a4        NaN         NaN

In [ ]:
uno_2.merge(otro_2, left_on='nombre_uno', right_on='nombre_dos', how='right').drop('nombre_dos', axis=1)

  nombre_uno       dirección    teléfono
0        ras  calle fantasía  7245689247
1        ana              a2          b1
2      sonia              a1          b2

## Join
El join, a diferencia del merge, va a unir los dataframes y donde no haya registros en el "índice" va a poner NaN

In [ ]:
uno=pd.DataFrame({'key': ['k0', 'k1', 'k2', 'k3', 'k4'],
                  'A': ['a0', 'a1', 'a2', 'a3', 'a4']})

otro=pd.DataFrame({'key': ['k0', 'k1', 'k2'],
                  'B': ['b0', 'b1', 'b2']})

In [ ]:
uno

  key   A
0  k0  a0
1  k1  a1
2  k2  a2
3  k3  a3
4  k4  a4

In [ ]:
otro

  key   B
0  k0  b0
1  k1  b1
2  k2  b2

In [ ]:
uno.join(otro, lsuffix='_uno', rsuffix='_dos')

  key_uno   A key_dos    B
0      k0  a0      k0   b0
1      k1  a1      k1   b1
2      k2  a2      k2   b2
3      k3  a3     NaN  NaN
4      k4  a4     NaN  NaN

In [ ]:
otro.join(uno, lsuffix='_uno', rsuffix='_dos')

  key_uno   B key_dos   A
0      k0  b0      k0  a0
1      k1  b1      k1  a1
2      k2  b2      k2  a2

In [ ]:
uno.join(otro, lsuffix='_uno', rsuffix='_dos', how='right')

In [ ]:
otro.join(uno, lsuffix='_uno', rsuffix='_dos', how='right')

  key_uno    B key_dos   A
0      k0   b0      k0  a0
1      k1   b1      k1  a1
2      k2   b2      k2  a2
3     NaN  NaN      k3  a3
4     NaN  NaN      k4  a4

In [ ]:
type(uno.join(otro, lsuffix='_uno', rsuffix='_dos'))

## Exportar datos

In [ ]:
otro.to_csv('../datasets/pandas_merge.csv')

## Métodos habituales de pandas
```python
df.head()                     # printea la cabeza, por defecto 5 filas
df.tail()                     # pritea la cola, por defecto 5 filas
df.describe()                 # descripcion estadistica
df.info()                     # informacion del df
df.info(memory_usage='deep')
df.columns                    # muestra columna
df.index                      # muestra indice
df.dtypes                     # muestra tipos de datos de las columnas
df.plot()                     # hace un grafico
df.hist()                     # hace un histograma
df.col.value_counts()         # cuenta los valores unicos de una columna
df.col.unique()               # muestra valores unicos de una columna
df.copy()                     # copia el df
df.drop()                     # elimina columnas o filas (axis=0,1)
df.dropna()                   # elimina nulos
df.fillna()                   # rellena nulos
df.shape                      # dimensiones del df
df._get_numeric_data()        # selecciona columnas numericas
df.rename()                   # renombre columnas
df.str.replace()              # reemplaza columnas de strings
df.astype(dtype='float32')    # cambia el tipo de dato
df.iloc[]                     # localiza por indice
df.loc[]                      # localiza por elemento
df.transpose()                # transpone el df
df.T
df.sample(n, frac)            # muestra del df
df.col.sum()                  # suma de una columna
df.col.max()                  # maximo de una columna
df.col.min()                  # minimo de una columna
df[col]                       # selecciona columna
df.col
df.isnull()                   # valores nulos
df.isna()
df.notna()                    # valores no nulos
df.drop_duplicates()          # eliminar duplicados
df.reset_index(inplace=True)  # resetea el indice y sobreescribe
```

## Further materials

* [Read the docs!](https://pandas.pydata.org/pandas-docs/stable/index.html)
* [Cheatsheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)
* [Exercises to practice](https://github.com/guipsamora/pandas_exercises)
* [More on merge, concat, and join](https://realpython.com/pandas-merge-join-and-concat/#pandas-join-combining-data-on-a-column-or-index). And [even more!](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html)

In [ ]:
# tienes problemas para importar los datos con el CSV?
# a veces se separa por '|' otras por ',' (valor por defecto), otras por ';', otras por tabulador '\t'

# read_csv(datos, sep= '|') ---> o el tipo de separador que sea


# si el separador es '\t'
# read_table(datos)

![aquí nos hemos quedado](https://media.tenor.com/ZzhRs6kpGGMAAAAC/you-shall-not-pass-gandalf.gif)